"""Partial type stubs for ROOT (PyROOT) as used in FairShip.

Only methods actually observed in the FairShip codebase are stubbed.
Do NOT add module-level __getattr__ — let pyrefly flag missing attributes
so we know what to add.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, overload

# ---------------------------------------------------------------------------
# Submodules (re-exported so ROOT.genfit, ROOT.std, etc. resolve)
# ---------------------------------------------------------------------------
from ROOT import Math as Math
from ROOT import Pythia8 as Pythia8
from ROOT import genfit as genfit
from ROOT import std as std

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------
def addressof(obj: Any, member: str = ...) -> int: ...
def SetOwnership(obj: Any, ownership: bool) -> None: ...
def EnableImplicitMT(nthreads: int = ...) -> None: ...
def RDataFrame(tree_name: str, file_name: str | list[str]) -> Any: ...

# ---------------------------------------------------------------------------
# Constants — colours
# ---------------------------------------------------------------------------
kWhite: int
kBlack: int
kGray: int
kRed: int
kGreen: int
kBlue: int
kYellow: int
kMagenta: int
kCyan: int
kOrange: int
kSpring: int
kTeal: int
kAzure: int
kViolet: int
kPink: int

# ---------------------------------------------------------------------------
# Constants — booleans / severity
# ---------------------------------------------------------------------------
kTRUE: bool
kFALSE: bool
kWarning: int
kInfo: int
kError: int

# ---------------------------------------------------------------------------
# Constants — marker styles
# ---------------------------------------------------------------------------
kFullCircle: int
kOpenCircle: int
kFullSquare: int
kOpenSquare: int
kFullTriangleUp: int
kFullTriangleDown: int
kOpenTriangleUp: int
kFullDotSmall: int
kFullDotMedium: int
kFullDotLarge: int
kFullDiamond: int

# ---------------------------------------------------------------------------
# Constants — GUI layout hints
# ---------------------------------------------------------------------------
kLHintsExpandX: int
kLHintsExpandY: int
kLocalCleanup: int
kDeepCleanup: int

# ---------------------------------------------------------------------------
# Global error ignore level
# ---------------------------------------------------------------------------
gErrorIgnoreLevel: int

# ---------------------------------------------------------------------------
# TMath
# ---------------------------------------------------------------------------
class TMath:  # Partial stub
    @staticmethod
    def Sqrt(x: float) -> float: ...
    @staticmethod
    def Power(base: float, exp: float) -> float: ...
    @staticmethod
    def Abs(x: float) -> float: ...
    @staticmethod
    def Log(x: float) -> float: ...
    @staticmethod
    def Log10(x: float) -> float: ...
    @staticmethod
    def Exp(x: float) -> float: ...
    @staticmethod
    def Sin(x: float) -> float: ...
    @staticmethod
    def Cos(x: float) -> float: ...
    @staticmethod
    def Tan(x: float) -> float: ...
    @staticmethod
    def ATan2(y: float, x: float) -> float: ...
    @staticmethod
    def Pi() -> float: ...
    @staticmethod
    def C() -> float: ...
    @staticmethod
    def Prob(chi2: float, ndf: int) -> float: ...
    @staticmethod
    def ACos(x: float) -> float: ...
    @staticmethod
    def ASin(x: float) -> float: ...
    @staticmethod
    def Min(a: float, b: float) -> float: ...
    @staticmethod
    def Max(a: float, b: float) -> float: ...
    @staticmethod
    def PiOver2() -> float: ...

# ===========================================================================
# Core ROOT classes
# ===========================================================================

class TObject:  # Partial stub
    kSingleKey: int
    kOverwrite: int
    def GetName(self) -> str: ...
    def GetTitle(self) -> str: ...
    def Clone(self, newname: str = ...) -> TObject: ...
    def Write(self, name: str = ..., option: int = ..., bufsize: int = ...) -> int: ...
    def Draw(self, option: str = ...) -> None: ...
    def Class(self) -> Any: ...
    def ClassName(self) -> str: ...
    def IsOpen(self) -> bool: ...
    def IsWritable(self) -> bool: ...
    def Close(self, option: str = ...) -> None: ...

class TDirectory(TObject):  # Partial stub
    def cd(self, path: str = ...) -> bool: ...
    def Get(self, namecycle: str) -> Any: ...
    def GetListOfKeys(self) -> Any: ...
    def FindObjectAny(self, name: str) -> TObject | None: ...
    def FindObject(self, name: str) -> TObject | None: ...

class TFile(TDirectory):  # Partial stub
    @overload
    def __init__(self, name: str, option: str = ..., title: str = ..., compress: int = ...) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @staticmethod
    def Open(name: str, option: str = ..., title: str = ..., compress: int = ..., netopt: int = ...) -> TFile: ...
    def Close(self, option: str = ...) -> None: ...
    def Write(  # pyrefly: ignore[bad-param-name-override]
        self, name: str = ..., option: int = ..., bufsiz: int = ...
    ) -> int: ...
    def WriteObject(self, obj: Any, name: str, option: str = ...) -> int: ...
    def GetListOfKeys(self) -> Any: ...
    def FindObjectAny(self, name: str) -> TObject | None: ...
    def Get(self, namecycle: str) -> Any: ...
    def GetKey(self, name: str, cycle: int = ...) -> Any: ...
    def FindKey(self, name: str) -> Any: ...
    def ReadKeys(self) -> int: ...
    def IsZombie(self) -> bool: ...
    def IsOpen(self) -> bool: ...
    def SetWritable(self, writable: bool = ...) -> None: ...
    def Flush(self) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    # TFile supports attribute access for trees/objects (e.g. f.cbmsim)
    def __getattr__(self, name: str) -> Any: ...
    # PyROOT TFile supports context manager protocol
    def __enter__(self) -> TFile: ...
    def __exit__(self, *args: Any) -> None: ...

class TMemFile(TFile):  # Partial stub
    def __init__(self, name: str, option: str = ...) -> None: ...

# ---------------------------------------------------------------------------
# TTree / TChain / TNtuple
# ---------------------------------------------------------------------------
class TTree(TObject):  # Partial stub
    def __init__(self, name: str = ..., title: str = ...) -> None: ...
    @overload
    def Branch(self, name: str, obj: Any, bufsize: int = ..., splitlevel: int = ...) -> TBranch: ...
    @overload
    def Branch(self, name: str, obj: Any, leaflist: str) -> TBranch: ...
    def GetBranch(self, name: str) -> TBranch | None: ...
    def SetBranchStatus(self, name: str, status: int) -> None: ...
    def SetBranchAddress(self, name: str, addr: Any) -> int: ...
    def GetEvent(self, entry: int, getall: int = ...) -> int: ...
    def GetEntries(self) -> int: ...
    def GetEntriesFast(self) -> int: ...
    def Fill(self) -> int: ...
    def Write(self, name: str = ..., option: int = ..., bufsize: int = ...) -> int: ...
    def Draw(  # type: ignore[override]  # pyrefly: ignore[bad-override]
        self, varexp: str, selection: str = ..., option: str = ..., nentries: int = ..., firstentry: int = ...
    ) -> int: ...
    def GetListOfBranches(self) -> Any: ...
    def GetListOfLeaves(self) -> Any: ...
    def GetCurrentFile(self) -> TFile: ...
    def CloneTree(self, nentries: int = ..., option: str = ...) -> TTree: ...
    def SetDirectory(self, directory: TDirectory) -> None: ...
    def GetDirectory(self) -> TDirectory: ...
    def GetEntry(self, entry: int, getall: int = ...) -> int: ...
    def SetEventList(self, elist: TEntryList | None) -> None: ...
    def AddFriend(self, tree: TTree | str, alias: str = ...) -> None: ...
    # Dynamic branch access (e.g. tree.MCTrack, tree.strawtubesPoint)
    def __getattr__(self, name: str) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...

class TBranch(TObject):  # Partial stub
    def GetEntry(self, entry: int, getall: int = ...) -> int: ...
    def SetAddress(self, addr: Any) -> None: ...
    def GetListOfLeaves(self) -> Any: ...
    def Fill(self) -> int: ...

class TLeaf(TObject):  # Partial stub
    def GetValue(self, i: int = ...) -> float: ...
    def GetTypeName(self) -> str: ...

class TChain(TTree):  # Partial stub
    def __init__(self, name: str = ..., title: str = ...) -> None: ...
    def Add(self, name: str, nentries: int = ...) -> int: ...
    def GetFile(self) -> TFile: ...

class TNtuple(TTree):  # Partial stub
    def __init__(self, name: str = ..., title: str = ..., varlist: str = ...) -> None: ...
    def Fill(self, *args: Any) -> int: ...  # type: ignore[override]

class TEntryList(TObject):  # Partial stub
    def __init__(self, tree: TTree = ...) -> None: ...
    def GetN(self) -> int: ...
    def GetEntry(self, index: int) -> int: ...

# ---------------------------------------------------------------------------
# Histograms
# ---------------------------------------------------------------------------
class TH1(TObject):  # Partial stub
    def Fill(self, x: float, w: float = ...) -> int: ...
    def Draw(self, option: str = ...) -> None: ...
    def GetEntries(self) -> float: ...
    def GetMean(self, axis: int = ...) -> float: ...
    def GetRMS(self, axis: int = ...) -> float: ...
    def GetBinContent(self, bin: int) -> float: ...
    def SetBinContent(self, bin: int, content: float) -> None: ...
    def GetBinError(self, bin: int) -> float: ...
    def GetNbinsX(self) -> int: ...
    def GetXaxis(self) -> Any: ...
    def GetYaxis(self) -> Any: ...
    def SetDirectory(self, dir: TDirectory | TROOT) -> None: ...
    def SetMarkerColor(self, color: int) -> None: ...
    def SetMarkerStyle(self, style: int) -> None: ...
    def SetMarkerSize(self, size: float) -> None: ...
    def SetLineColor(self, color: int) -> None: ...
    def SetLineStyle(self, style: int) -> None: ...
    def SetLineWidth(self, width: int) -> None: ...
    def SetFillColor(self, color: int) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def SetName(self, name: str) -> None: ...
    def Add(self, h: TH1, c: float = ...) -> bool: ...
    def Scale(self, c: float, option: str = ...) -> None: ...
    def Sumw2(self, flag: bool = ...) -> None: ...
    def GetSumw2N(self) -> int: ...
    def Reset(self, option: str = ...) -> None: ...
    def Clone(self, newname: str = ...) -> TH1: ...
    def Fit(
        self, f1: str | TF1 = ..., option: str = ..., goption: str = ..., xmin: float = ..., xmax: float = ...
    ) -> int: ...
    def Write(self, name: str = ..., option: int = ..., bufsize: int = ...) -> int: ...
    def Integral(self, binx1: int = ..., binx2: int = ..., option: str = ...) -> float: ...
    def Rebin(self, ngroup: int = ..., newname: str = ...) -> TH1: ...
    def GetFunction(self, name: str) -> TF1: ...
    def SetStats(self, stats: bool | int) -> None: ...
    def SetXTitle(self, title: str) -> None: ...
    def SetYTitle(self, title: str) -> None: ...
    def SetZTitle(self, title: str) -> None: ...
    def Chi2Test(self, h2: TH1, option: str = ...) -> float: ...
    def KolmogorovTest(self, h2: TH1, option: str = ...) -> float: ...

class TH1I(TH1):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, title: str, nbinsx: int, xlow: float, xup: float) -> None: ...

class TH1D(TH1):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, title: str, nbinsx: int, xlow: float, xup: float) -> None: ...

class TH1F(TH1):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, title: str, nbinsx: int, xlow: float, xup: float) -> None: ...

class TH2(TH1):  # Partial stub
    @overload  # type: ignore[override]
    def Fill(self, x: float, y: float) -> int: ...  # pyrefly: ignore[bad-override]
    @overload
    def Fill(self, x: float, y: float, w: float) -> int: ...
    def GetNbinsY(self) -> int: ...
    def GetBinContent(self, binx: int, biny: int = ...) -> float: ...  # type: ignore[override]
    def SetBinContent(self, binx: int, biny_or_content: int | float, content: float = ...) -> None: ...  # type: ignore[override]
    def ProjectionX(self, name: str = ..., firstybin: int = ..., lastybin: int = ..., option: str = ...) -> TH1D: ...
    def ProjectionY(self, name: str = ..., firstxbin: int = ..., lastxbin: int = ..., option: str = ...) -> TH1D: ...

class TH2D(TH2):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, name: str, title: str, nbinsx: int, xlow: float, xup: float, nbinsy: int, ylow: float, yup: float
    ) -> None: ...

class TH2F(TH2):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, name: str, title: str, nbinsx: int, xlow: float, xup: float, nbinsy: int, ylow: float, yup: float
    ) -> None: ...

class TH2I(TH2):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, name: str, title: str, nbinsx: int, xlow: float, xup: float, nbinsy: int, ylow: float, yup: float
    ) -> None: ...

class TH3(TH1):  # Partial stub
    def Fill(self, x: float, y: float, z: float, w: float = ...) -> int: ...  # type: ignore[override]
    def GetNbinsY(self) -> int: ...
    def GetNbinsZ(self) -> int: ...
    def Project3D(self, option: str) -> TH1: ...

class TH3D(TH3):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        title: str,
        nbinsx: int,
        xlow: float,
        xup: float,
        nbinsy: int,
        ylow: float,
        yup: float,
        nbinsz: int,
        zlow: float,
        zup: float,
    ) -> None: ...

class TH3F(TH3):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        title: str,
        nbinsx: int,
        xlow: float,
        xup: float,
        nbinsy: int,
        ylow: float,
        yup: float,
        nbinsz: int,
        zlow: float,
        zup: float,
    ) -> None: ...

class TProfile(TH1):  # Partial stub
    @overload
    def __init__(self, name: str, title: str, nbinsx: int, xlow: float, xup: float, option: str = ...) -> None: ...
    @overload
    def __init__(
        self, name: str, title: str, nbinsx: int, xlow: float, xup: float, ylow: float, yup: float, option: str = ...
    ) -> None: ...

# ---------------------------------------------------------------------------
# Graphics / Drawing
# ---------------------------------------------------------------------------
class TCanvas(TObject):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, title: str = ..., ww: int = ..., wh: int = ...) -> None: ...
    def Divide(self, nx: int, ny: int = ..., xmargin: float = ..., ymargin: float = ...) -> None: ...
    def cd(self, subpad: int = ...) -> Any: ...
    def Update(self) -> None: ...
    def SaveAs(self, filename: str, option: str = ...) -> None: ...
    def Print(self, filename: str, option: str = ...) -> None: ...
    def Draw(self, option: str = ...) -> None: ...
    def SetLogy(self, value: int = ...) -> None: ...
    def SetLogx(self, value: int = ...) -> None: ...
    def SetGridx(self, value: int = ...) -> None: ...
    def SetGridy(self, value: int = ...) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def SetRightMargin(self, margin: float) -> None: ...
    def ToggleEditor(self) -> None: ...
    def Write(self, name: str = ..., option: int = ..., bufsize: int = ...) -> int: ...
    def Clone(self, newname: str = ...) -> TCanvas: ...

class TGraph(TObject):  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, filename: str, format: str = ..., option: str = ...) -> None: ...
    def SetPoint(self, i: int, x: float, y: float) -> None: ...
    def Draw(self, option: str = ...) -> None: ...
    def SetMarkerColor(self, color: int) -> None: ...
    def SetMarkerStyle(self, style: int) -> None: ...
    def SetMarkerSize(self, size: float) -> None: ...
    def SetLineColor(self, color: int) -> None: ...
    def SetLineWidth(self, width: int) -> None: ...
    def SetName(self, name: str) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def GetN(self) -> int: ...
    def Eval(self, x: float, spline: Any = ..., option: str = ...) -> float: ...

class TF1(TObject):  # Partial stub
    @overload
    def __init__(self, name: str, formula: str, xmin: float = ..., xmax: float = ...) -> None: ...
    @overload
    def __init__(self, name: str, fcn: Any, xmin: float, xmax: float, npar: int) -> None: ...
    def SetParameter(self, par: int, value: float) -> None: ...
    def GetParameter(self, par: int) -> float: ...
    def SetParameters(self, *args: float) -> None: ...
    def SetParLimits(self, ipar: int, parmin: float, parmax: float) -> None: ...
    def Eval(self, x: float) -> float: ...
    def Draw(self, option: str = ...) -> None: ...
    def SetLineColor(self, color: int) -> None: ...
    def SetNpx(self, npx: int) -> None: ...
    def SetParName(self, ipar: int, name: str) -> None: ...
    def GetParName(self, i: int) -> str: ...
    def GetParError(self, i: int) -> float: ...
    def GetNpar(self) -> int: ...

class TLegend(TObject):  # Partial stub
    def __init__(self, x1: float, y1: float, x2: float, y2: float, header: str = ..., option: str = ...) -> None: ...
    def AddEntry(self, obj: TObject | str, label: str, option: str = ...) -> Any: ...
    def Draw(self, option: str = ...) -> None: ...
    def SetBorderSize(self, size: int) -> None: ...

class TLatex(TObject):  # Partial stub
    def __init__(self, x: float = ..., y: float = ..., text: str = ...) -> None: ...
    def DrawLatex(self, x: float, y: float, text: str) -> TLatex: ...
    def DrawLatexNDC(self, x: float, y: float, text: str) -> TLatex: ...
    def SetTextSize(self, size: float) -> None: ...
    def SetTextColor(self, color: int) -> None: ...
    def SetTextFont(self, font: int) -> None: ...

class TText(TObject):  # Partial stub
    def __init__(self, x: float = ..., y: float = ..., text: str = ...) -> None: ...
    def SetTextSize(self, size: float) -> None: ...
    def SetTextColor(self, color: int) -> None: ...
    def SetTextAngle(self, angle: float) -> None: ...
    def SetTextAlign(self, align: int) -> None: ...
    def Draw(self, option: str = ...) -> None: ...

class TSpline(TObject):  # Partial stub
    def Eval(self, x: float) -> float: ...

class TSpline3(TSpline):  # Partial stub
    ...
class TSpline5(TSpline):  # Partial stub
    ...

# ---------------------------------------------------------------------------
# Vectors / Matrices
# ---------------------------------------------------------------------------
class TVector3:  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def X(self) -> float: ...
    def Y(self) -> float: ...
    def Z(self) -> float: ...
    # PyROOT also exposes lowercase property access
    def x(self) -> float: ...
    def y(self) -> float: ...
    def z(self) -> float: ...
    def Px(self) -> float: ...
    def Py(self) -> float: ...
    def Pz(self) -> float: ...
    def Mag(self) -> float: ...
    def Mag2(self) -> float: ...
    def Unit(self) -> TVector3: ...
    def Dot(self, other: TVector3) -> float: ...
    def Cross(self, other: TVector3) -> TVector3: ...
    def Angle(self, other: TVector3) -> float: ...
    def Phi(self) -> float: ...
    def Theta(self) -> float: ...
    def Eta(self) -> float: ...
    def Pt(self) -> float: ...
    def SetXYZ(self, x: float, y: float, z: float) -> None: ...
    def __sub__(self, other: TVector3) -> TVector3: ...
    def __add__(self, other: TVector3) -> TVector3: ...
    def __mul__(self, scalar: float) -> TVector3: ...
    def __call__(self, i: int) -> float: ...
    def __getitem__(self, idx: int) -> float: ...
    def Print(self, option: str = ...) -> None: ...

class TLorentzVector:  # Partial stub
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, t: float) -> None: ...
    @overload
    def __init__(self, v: TVector3, t: float) -> None: ...
    def X(self) -> float: ...
    def Y(self) -> float: ...
    def Z(self) -> float: ...
    def Px(self) -> float: ...
    def Py(self) -> float: ...
    def Pz(self) -> float: ...
    def E(self) -> float: ...
    def P(self) -> float: ...
    def M(self) -> float: ...
    def M2(self) -> float: ...
    def Mag(self) -> float: ...
    def Pt(self) -> float: ...
    def Eta(self) -> float: ...
    def Phi(self) -> float: ...
    def Vect(self) -> TVector3: ...
    def Rapidity(self) -> float: ...
    def SetPxPyPzE(self, px: float, py: float, pz: float, e: float) -> None: ...
    def SetXYZM(self, x: float, y: float, z: float, m: float) -> None: ...
    def __add__(self, other: TLorentzVector) -> TLorentzVector: ...
    def __sub__(self, other: TLorentzVector) -> TLorentzVector: ...
    def __call__(self, i: int) -> float: ...
    def Dot(self, other: TLorentzVector) -> float: ...

class TRotation:  # Partial stub
    def __init__(self) -> None: ...
    def __mul__(self, other: TVector3) -> TVector3: ...
    def RotateX(self, angle: float) -> TRotation: ...
    def RotateY(self, angle: float) -> TRotation: ...
    def RotateZ(self, angle: float) -> TRotation: ...

class TVectorD:  # Partial stub
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, n: int, data: Any) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, val: float) -> None: ...
    def GetNrows(self) -> int: ...
    def Zero(self) -> TVectorD: ...
    def Print(self, option: str = ...) -> None: ...

class TMatrixD:  # Partial stub
    def __init__(self, nrows: int, ncols: int) -> None: ...
    def __getitem__(self, i: int) -> Any: ...
    def Mult(self, a: TMatrixD, b: TMatrixD) -> None: ...
    def Transpose(self, src: TMatrixD) -> TMatrixD: ...

class TMatrixDSym:  # Partial stub
    def __init__(self, n: int = ...) -> None: ...
    def __getitem__(self, i: int) -> Any: ...
    def Invert(self) -> TMatrixDSym: ...
    def Determinant(self) -> float: ...

# ---------------------------------------------------------------------------
# Particle database / random
# ---------------------------------------------------------------------------
class TDatabasePDG:  # Partial stub
    @staticmethod
    def Instance() -> TDatabasePDG: ...
    def GetParticle(self, pdg: int | str) -> TParticlePDG | None: ...
    def AddParticle(
        self,
        name: str,
        title: str,
        mass: float,
        stable: bool,
        width: float,
        charge: str | int | float,
        particle_class: str,
        pdgcode: int,
        anti: int = ...,
        tracking_code: int = ...,
    ) -> TParticlePDG: ...

class TParticlePDG:  # Partial stub
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def Mass(self) -> float: ...
    def Charge(self) -> float: ...
    def Width(self) -> float: ...
    def Lifetime(self) -> float: ...
    def PdgCode(self) -> int: ...

class TParticle(TObject):  # Partial stub
    def GetPdgCode(self) -> int: ...
    def GetMass(self) -> float: ...
    def GetMotherId(self) -> int: ...
    def GetFirstMother(self) -> int: ...
    def GetSecondMother(self) -> int: ...
    def GetFirstDaughter(self) -> int: ...
    def GetLastDaughter(self) -> int: ...
    def Px(self) -> float: ...
    def Py(self) -> float: ...
    def Pz(self) -> float: ...
    def Energy(self) -> float: ...
    def P(self) -> float: ...
    def Pt(self) -> float: ...
    def Vx(self) -> float: ...
    def Vy(self) -> float: ...
    def Vz(self) -> float: ...

class TRandom(TObject):  # Partial stub
    def __init__(self, seed: int = ...) -> None: ...
    def Rndm(self) -> float: ...
    def Gaus(self, mean: float = ..., sigma: float = ...) -> float: ...
    def Uniform(self, x1: float = ..., x2: float = ...) -> float: ...
    def SetSeed(self, seed: int = ...) -> None: ...
    def GetSeed(self) -> int: ...
    def Exp(self, tau: float) -> float: ...

class TRandom3(TRandom):  # Partial stub
    def __init__(self, seed: int = ...) -> None: ...

class TStopwatch(TObject):  # Partial stub
    def __init__(self) -> None: ...
    def Start(self, reset: bool = ...) -> None: ...
    def Stop(self) -> None: ...
    def RealTime(self) -> float: ...
    def CpuTime(self) -> float: ...
    def Print(self, option: str = ...) -> None: ...

class TMinuit(TObject):  # Partial stub
    def __init__(self, maxpar: int = ...) -> None: ...
    def DefineParameter(
        self, parNo: int, name: str, initVal: float, initErr: float, lowerLimit: float, upperLimit: float
    ) -> int: ...
    def SetFCN(self, fcn: Any) -> None: ...
    def Command(self, command: str) -> int: ...
    def Migrad(self) -> int: ...
    def GetParameter(self, parNo: int, currentValue: Any, currentError: Any) -> int: ...
    def SetPrintLevel(self, level: int) -> None: ...
    def Clear(self) -> None: ...
    def mnexcm(self, cmd: str, arglist: Any, narg: int, ierflg: Any) -> None: ...
    def mnemat(self, matrix: Any, ndim: int) -> None: ...

# ---------------------------------------------------------------------------
# Collections
# ---------------------------------------------------------------------------
class TClonesArray(TObject):  # Partial stub
    def __init__(self, classname: str, size: int = ...) -> None: ...
    def GetEntries(self) -> int: ...
    def GetEntriesFast(self) -> int: ...
    def GetSize(self) -> int: ...
    def At(self, idx: int) -> TObject: ...
    def __getitem__(self, idx: int) -> Any: ...
    def __setitem__(self, idx: int, obj: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def ConstructedAt(self, idx: int) -> Any: ...
    def Clear(self, option: str = ...) -> None: ...
    def Delete(self, option: str = ...) -> None: ...
    def Expand(self, newSize: int) -> None: ...
    def Dump(self) -> None: ...

class TList(TObject):  # Partial stub
    def __init__(self) -> None: ...
    def Add(self, obj: TObject) -> None: ...
    def At(self, idx: int) -> TObject: ...
    def __getitem__(self, idx: int) -> Any: ...
    def GetEntries(self) -> int: ...
    def FindObject(self, name: str) -> TObject | None: ...
    def SetName(self, name: str) -> None: ...
    def __iter__(self) -> Iterator[TObject]: ...
    def __len__(self) -> int: ...

class TObjString(TObject):  # Partial stub
    def __init__(self, s: str = ...) -> None: ...
    def GetString(self) -> str: ...

# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------
class TGeoManager(TObject):  # Partial stub
    def GetTopVolume(self) -> TGeoVolume: ...
    def GetTopNode(self) -> TGeoNode: ...
    def GetVolume(self, name: str) -> TGeoVolume: ...
    def GetListOfVolumes(self) -> Any: ...
    def GetListOfNodes(self) -> Any: ...
    def CloseGeometry(self, option: str = ...) -> None: ...
    def Export(self, filename: str, name: str = ..., option: str = ...) -> int: ...
    def Import(self, filename: str) -> TGeoManager: ...
    def CheckOverlaps(self, ovlp: float = ..., option: str = ...) -> None: ...
    def PrintOverlaps(self) -> None: ...
    def SetVisLevel(self, level: int) -> None: ...
    def SetVerboseLevel(self, level: int) -> None: ...
    def GetVerboseLevel(self) -> int: ...
    def FindVolumeFast(self, name: str, multi: bool = ...) -> TGeoVolume: ...
    def FindNode(self, x: float, y: float, z: float) -> TGeoNode: ...
    def GetCurrentNavigator(self) -> Any: ...
    def GetMedium(self, name: str | float = ...) -> Any: ...
    def GetMaterial(self, name: str | float = ...) -> Any: ...
    def MakeBox(self, name: str, medium: Any, dx: float, dy: float, dz: float) -> TGeoVolume: ...
    def SetNmeshPoints(self, n: int) -> None: ...

class TGeoVolume(TObject):  # Partial stub
    def GetName(self) -> str: ...
    def GetNodes(self) -> Any: ...
    def GetNumber(self) -> int: ...
    def GetField(self) -> Any: ...
    def GetShape(self) -> Any: ...
    def GetMedium(self) -> Any: ...
    def GetMaterial(self) -> Any: ...
    def AddNode(self, volume: TGeoVolume, copy_no: int, matrix: TGeoTranslation | None = ...) -> TGeoNode: ...
    def GetNode(self, name_or_index: str | int) -> TGeoNode: ...
    def FindNode(self, name: str) -> TGeoNode | None: ...
    def GetNdaughters(self) -> int: ...
    def SetVisibility(self, vis: bool | int) -> None: ...
    def SetVisDaughters(self, vis: bool | int) -> None: ...
    def Draw(self, option: str = ...) -> None: ...
    def GetDX(self) -> float: ...
    def GetDY(self) -> float: ...
    def GetDZ(self) -> float: ...

class TGeoNode(TObject):  # Partial stub
    def GetName(self) -> str: ...
    def GetVolume(self) -> TGeoVolume: ...
    def GetNumber(self) -> int: ...
    def GetNdaughters(self) -> int: ...
    def GetDaughter(self, ind: int) -> TGeoNode: ...
    def GetNodes(self) -> Any: ...
    def GetMatrix(self) -> TGeoMatrix: ...
    def IsVisible(self) -> int: ...
    def IsVisDaughters(self) -> int: ...
    def SetVisibility(self, vis: int) -> None: ...
    def SetVisDaughters(self, vis: int) -> None: ...

class TGeoMatrix:  # Partial stub
    def GetTranslation(self) -> Any: ...

class TGeoTranslation(TGeoMatrix):  # Partial stub
    def __init__(self, dx: float = ..., dy: float = ..., dz: float = ...) -> None: ...

# ---------------------------------------------------------------------------
# GUI / Global classes
# ---------------------------------------------------------------------------
class TROOT(TDirectory):  # Partial stub
    def SetBatch(self, batch: bool = ...) -> None: ...
    def ProcessLine(self, line: str) -> int: ...
    def LoadMacro(self, filename: str, error: Any = ..., check: bool = ...) -> int: ...
    def FindObject(self, name: str) -> TObject | None: ...
    def FindObjectAny(self, name: str) -> TObject | None: ...
    def GetListOfFiles(self) -> TList: ...
    def GetListOfGlobals(self, load: bool = ...) -> Any: ...
    def cd(self, path: str = ...) -> bool: ...
    def GetVersionInt(self) -> int: ...
    def SetWebDisplay(self, opt: str) -> None: ...

class TSystem(TObject):  # Partial stub
    def Load(self, module: str, entry: str = ..., system: bool = ...) -> int: ...
    def Getenv(self, name: str) -> str: ...
    def Exec(self, shellcmd: str) -> int: ...
    def Exit(self, code: int, mode: bool = ...) -> None: ...

class TStyle(TObject):  # Partial stub
    def SetOptStat(self, stat: int | str = ...) -> None: ...
    def SetOptFit(self, fit: int = ...) -> None: ...
    def SetPalette(self, ncolors: int = ..., colors: Any = ...) -> None: ...
    def SetPadRightMargin(self, margin: float) -> None: ...

class TEnv(TObject):  # Partial stub
    def SetValue(self, name: str, value: str | int | float, level: int = ...) -> None: ...
    def GetValue(self, name: str, default: str) -> str: ...

class TInterpreter:  # Partial stub
    def ProcessLine(self, line: str) -> int: ...
    def Declare(self, code: str) -> bool: ...
    def AddIncludePath(self, path: str) -> None: ...

# ---------------------------------------------------------------------------
# Global objects
# ---------------------------------------------------------------------------
gROOT: TROOT
gSystem: TSystem
gRandom: TRandom
gGeoManager: TGeoManager
gStyle: TStyle
gInterpreter: TInterpreter
gEnv: TEnv
gMinuit: TMinuit

# ---------------------------------------------------------------------------
# EVE (Event Visualisation Environment)
# ---------------------------------------------------------------------------
class TEveElement:  # Partial stub
    def SetPickable(self, p: bool) -> None: ...
    def SetMainColor(self, color: int) -> None: ...
    def SetElementName(self, name: str) -> None: ...
    def SetName(self, name: str) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def SetVisLevel(self, level: int) -> None: ...
    def FindChild(self, name: str) -> TEveElement: ...
    def AddElement(self, el: TEveElement) -> None: ...
    def DestroyElements(self) -> None: ...
    def GetName(self) -> str: ...
    def GetEditorObject(self) -> Any: ...
    def GetGLViewer(self) -> TGLViewer: ...

class TEveCompound(TEveElement):  # Partial stub
    def __init__(self, name: str = ..., title: str = ...) -> None: ...
    def OpenCompound(self) -> None: ...
    def CloseCompound(self) -> None: ...

class TEveLine(TEveElement):  # Partial stub
    def __init__(self, name: str = ...) -> None: ...
    def SetNextPoint(self, x: float, y: float, z: float) -> int: ...
    def SetLineColor(self, color: int) -> None: ...
    def SetLineWidth(self, width: int) -> None: ...

class TEveBox(TEveElement):  # Partial stub
    def __init__(self, name: str = ...) -> None: ...
    def SetVertex(self, i: int, x: float, y: float, z: float) -> None: ...

class TEveText(TEveElement):  # Partial stub
    def __init__(self, text: str = ...) -> None: ...
    def SetFontSize(self, size: int) -> None: ...
    def SetFontMode(self, mode: int) -> None: ...
    def SetLighting(self, lighting: bool) -> None: ...
    def SetMainColor(self, color: int) -> None: ...
    def PtrMainTrans(self) -> Any: ...
    def RefMainTrans(self) -> Any: ...

class TEvePointSet(TEveElement):  # Partial stub
    def __init__(self, name: str = ..., n: int = ...) -> None: ...
    def SetNextPoint(self, x: float, y: float, z: float) -> int: ...
    def SetMarkerColor(self, color: int) -> None: ...
    def SetMarkerStyle(self, style: int) -> None: ...
    def SetMarkerSize(self, size: float) -> None: ...

class TEveGeoTopNode(TEveElement):  # Partial stub
    def __init__(
        self, manager: TGeoManager, node: TGeoNode, visopt: int = ..., vislvl: int = ..., maxvisnds: int = ...
    ) -> None: ...

class TEveProjection:  # Partial stub
    kPT_RPhi: int
    kPT_RhoZ: int
    kPP_Plane: int
    def SetUsePreScale(self, use: bool) -> None: ...
    def AddPreScaleEntry(self, coord: int, max_val: float, scale: float) -> None: ...

class TEveProjectionManager(TEveElement):  # Partial stub
    def __init__(self, proj: int = ...) -> None: ...
    def SetProjection(self, proj: int) -> None: ...
    def GetProjection(self) -> TEveProjection: ...
    def ImportElements(self, el: TEveElement, scene: Any = ...) -> None: ...

class TEveProjectionAxes(TEveElement):  # Partial stub
    def __init__(self, mng: TEveProjectionManager) -> None: ...

class TEveWindow:  # Partial stub
    @staticmethod
    def CreateWindowInTab(tab: Any) -> Any: ...

class TEveViewer(TEveElement):  # Partial stub
    def __init__(self, name: str = ...) -> None: ...
    def AddScene(self, scene: Any) -> None: ...
    def GetGLViewer(self) -> TGLViewer: ...
    def SpawnGLEmbeddedViewer(self, border: int = ...) -> TGLViewer: ...
    def SetShowTitleBar(self, show: bool) -> None: ...
    def GetEveFrame(self) -> Any: ...
    def SetCurrentCamera(self, camera: int) -> None: ...

class TGLViewer:  # Partial stub
    kCameraOrthoXOY: int
    kCameraOrthoXOZ: int
    kCameraOrthoZOY: int
    kCameraOrthoZnOX: int
    kCameraPerspXOZ: int
    def CurrentCamera(self) -> Any: ...
    def SetCurrentCamera(self, camera: int) -> None: ...
    def SetStyle(self, style: int) -> None: ...
    def SetGuideState(self, axesType: int, axesDepthTest: bool, referenceOn: bool, referencePos: Any = ...) -> None: ...
    def SetSmoothPoints(self, s: bool) -> None: ...
    def SetSmoothLines(self, s: bool) -> None: ...
    def RequestDraw(self) -> None: ...
    def DoDraw(self, swap_buffers: bool = ...) -> None: ...
    def ResetCameras(self) -> None: ...
    def GetLightSet(self) -> Any: ...
    def GetFrame(self) -> Any: ...
    def SetName(self, name: str) -> None: ...

class TEveManager:  # Partial stub
    @staticmethod
    def Create(map_window: bool = ..., opt: str = ...) -> TEveManager: ...
    @staticmethod
    def Instance() -> TEveManager: ...
    def GetViewers(self) -> TEveElement: ...
    def GetScenes(self) -> TEveElement: ...
    def GetCurrentEvent(self) -> TEveElement: ...
    def GetDefaultGLViewer(self) -> TGLViewer: ...
    def GetDefaultViewer(self) -> TEveViewer: ...
    def SpawnNewScene(self, name: str, title: str = ...) -> Any: ...
    def SpawnNewViewer(self, name: str, title: str = ...) -> TEveViewer: ...
    def SpawnNewTab(self, name: str) -> Any: ...
    def GetBrowser(self) -> Any: ...
    def FullRedraw3D(self, resetCameras: bool = ..., dropLogicals: bool = ...) -> None: ...
    def AddToListTree(self, el: TEveElement, open: bool) -> None: ...
    def AddElement(self, el: TEveElement, parent: TEveElement = ...) -> None: ...
    def ElementChanged(self, el: TEveElement, update_scenes: bool = ..., redraw: bool = ...) -> None: ...
    def Redraw3D(self, resetCameras: bool = ..., dropLogicals: bool = ...) -> None: ...
    def GetEventScene(self) -> Any: ...
    def GetEditor(self) -> Any: ...

gEve: TEveManager

# ===========================================================================
# FairRoot classes (accessed via ROOT.FairRunSim etc.)
# ===========================================================================

class FairRunSim:  # Partial stub
    def __init__(self) -> None: ...
    def SetName(self, name: str) -> None: ...
    def SetSink(self, sink: FairRootFileSink) -> None: ...
    def SetSource(self, source: FairFileSource) -> None: ...
    def SetMaterials(self, filename: str) -> None: ...
    def SetUserConfig(self, config: str) -> None: ...
    def GetRuntimeDb(self) -> Any: ...
    def AddModule(self, module: Any) -> None: ...
    def SetGenerator(self, generator: FairPrimaryGenerator) -> None: ...
    def SetStoreTraj(self, store: bool) -> None: ...
    def SetField(self, field: Any) -> None: ...
    def SetPythiaDecayer(self, decayer: str) -> None: ...
    def Init(self) -> None: ...
    def Run(self, nEvents: int = ...) -> None: ...
    def GetListOfModules(self) -> Any: ...
    def GetGeoFile(self) -> TFile: ...
    def SetOutputFile(self, name: str) -> None: ...
    def CreateGeometryFile(self, filename: str) -> None: ...

class FairRunAna:  # Partial stub
    def __init__(self) -> None: ...
    def SetSource(self, source: FairFileSource) -> None: ...
    def SetSink(self, sink: FairRootFileSink) -> None: ...
    def SetGeomFile(self, filename: str) -> None: ...
    def GetRuntimeDb(self) -> Any: ...
    def GetGeoFile(self) -> TFile: ...
    def GetMainTask(self) -> FairTask: ...
    def Init(self) -> None: ...
    def Run(self, ev1: int = ..., ev2: int = ...) -> None: ...
    def Finish(self) -> None: ...

class FairTask(TObject):  # Partial stub
    def GetListOfTasks(self) -> TList: ...
    def SetName(self, name: str) -> None: ...

class FairPrimaryGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def SetTarget(self, z: float, spread: float) -> None: ...
    def SmearVertexXY(self, smear: bool) -> None: ...
    def SmearGausVertexXY(self, smear: bool) -> None: ...
    def SetBeam(self, x: float, y: float, sigmax: float, sigmay: float) -> None: ...
    def AddGenerator(self, gen: Any) -> None: ...

class FairBoxGenerator:  # Partial stub
    def __init__(self, pdgid: int, mult: int) -> None: ...
    def SetPRange(self, pmin: float, pmax: float) -> None: ...
    def SetPhiRange(self, phimin: float, phimax: float) -> None: ...
    def SetThetaRange(self, thetamin: float, thetamax: float) -> None: ...
    def SetXYZ(self, x: float, y: float, z: float) -> None: ...
    def SetBoxXYZ(self, x1: float, y1: float, x2: float, y2: float, z: float) -> None: ...

class FairFileSource:  # Partial stub
    def __init__(self, filename: str) -> None: ...
    def AddFriend(self, filename: str) -> None: ...

class FairRootFileSink:  # Partial stub
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, file: TFile | TMemFile) -> None: ...
    def WriteObject(self, obj: Any, name: str, option: int = ...) -> int: ...
    def SetOutTree(self, tree: TTree) -> None: ...

class FairRootManager:  # Partial stub
    @staticmethod
    def Instance() -> FairRootManager: ...
    def GetObject(self, name: str) -> Any: ...
    def GetInChain(self) -> TChain: ...

class FairParRootFileIo:  # Partial stub
    def __init__(self, check: bool = ...) -> None: ...
    def open(self, filename: str, option: str = ...) -> bool: ...

class FairEventHeader(TObject):  # Partial stub
    def __init__(self) -> None: ...
    def SetEventTime(self, t: float) -> None: ...
    def GetEventTime(self) -> float: ...
    def SetRunId(self, id: int) -> None: ...
    def GetRunID(self) -> int: ...
    def SetMCEntryNumber(self, n: int) -> None: ...
    def GetMCEntryNumber(self) -> int: ...

class FairEventManager(TObject):  # Partial stub
    def __init__(self) -> None: ...
    @staticmethod
    def Instance() -> FairEventManager: ...
    def SetMaxEnergy(self, e: float) -> None: ...
    def SetMinEnergy(self, e: float) -> None: ...
    def SetEvtMaxEnergy(self, e: float) -> None: ...
    def SetPriOnly(self, pri: bool) -> None: ...
    def AddTask(self, task: FairTask) -> None: ...
    def Init(self, visopt: int = ..., vislvl: int = ..., maxvisnds: int = ...) -> None: ...

class FairGeoLoader:  # Partial stub
    @staticmethod
    def Instance() -> FairGeoLoader: ...
    def getGeoInterface(self) -> Any: ...
    def getGeoBuilder(self) -> Any: ...

class FairBaseContFact:  # Partial stub
    def __init__(self) -> None: ...

class FairMCPoint(TObject):  # Partial stub
    def GetTrackID(self) -> int: ...
    def GetDetectorID(self) -> int: ...
    def GetX(self) -> float: ...
    def GetY(self) -> float: ...
    def GetZ(self) -> float: ...
    def GetPx(self) -> float: ...
    def GetPy(self) -> float: ...
    def GetPz(self) -> float: ...
    def GetTime(self) -> float: ...
    def GetEnergyLoss(self) -> float: ...
    def GetLength(self) -> float: ...

class VectorMCPointSource:  # Partial stub
    def __init__(self, points: Any = ..., name: str = ...) -> None: ...
    def __class_getitem__(cls, item: Any) -> Any: ...

class FairMCPointDraw(FairTask):  # Partial stub
    def __init__(self, name: str, source: Any = ..., colour: int = ..., marker: int = ...) -> None: ...

class FairMCTracksDraw(FairTask):  # Partial stub
    def __init__(self, name: str) -> None: ...

class FairGeoTracksDraw(FairTask):  # Partial stub
    def __init__(self, name: str) -> None: ...

class FairTrajFilter:  # Partial stub
    @staticmethod
    def Instance() -> FairTrajFilter: ...
    def SetStorePrimaries(self, store: bool) -> None: ...
    def SetStoreSecondaries(self, store: bool) -> None: ...
    def SetVertexCut(
        self, vxMin: float, vyMin: float, vzMin: float, vxMax: float, vyMax: float, vzMax: float
    ) -> None: ...
    def SetMomentumCutP(self, pMin: float = ..., pMax: float = ...) -> None: ...
    def SetEnergyCut(self, eMin: float, eMax: float) -> None: ...
    def SetStepSizeCut(self, stepMin: float) -> None: ...

class pyFairModule:  # Partial stub
    def __init__(self, module: Any) -> None: ...

# ===========================================================================
# FairShip-specific classes
# ===========================================================================

# --- Infrastructure ---

class ShipCave:  # Partial stub
    def __init__(self, name: str | float) -> None: ...
    def SetGeometryFileName(self, filename: str) -> None: ...
    def GetName(self) -> str: ...

class ShipTargetStation:  # Partial stub
    def __init__(
        self,
        name: str,
        length: float = ...,
        z: float = ...,
        nS: int = ...,
        HeT: float = ...,
        tz: float = ...,
        tl: float = ...,
    ) -> None: ...
    def SetLayerPosMat(
        self,
        xy: float = ...,
        slices_length: Any = ...,
        slices_gap: Any = ...,
        slices_material: Any = ...,
        d: Any = ...,
        L: Any = ...,
        G: Any = ...,
        M: Any = ...,
    ) -> None: ...
    def GetName(self) -> str: ...

class ShipMuonShield:  # Partial stub
    def __init__(
        self,
        in_params: Any = ...,
        params: Any = ...,
        z: float = ...,
        withConstField: bool = ...,
        WithConstShieldField: bool = ...,
        sc_mag: bool = ...,
        SC_key: bool = ...,
    ) -> None: ...
    def SetSNDSpace(self, hole: bool = ..., hole_dx: float = ..., hole_dy: float = ...) -> None: ...
    def GetName(self) -> str: ...

class ShipMagnet:  # Partial stub
    @overload
    def __init__(self, name: str, title: str, z: float) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        title: str,
        z: float,
        design: int,
        x: float,
        y: float,
        floorHeight: float,
        yokeWidth: float = ...,
        yokeDepth: float = ...,
        coilThick: float = ...,
    ) -> None: ...
    def GetName(self) -> str: ...

class ShipFieldMaker:  # Partial stub
    def __init__(self, verbose: bool = ...) -> None: ...
    def readInputFile(self, filename: str) -> None: ...
    def defineFieldMap(
        self, name: str, filename: str, position: TVector3, rotation: TVector3 = ..., quadSymm: bool = ...
    ) -> None: ...
    def defineComposite(self, name: str, *fields: str) -> None: ...
    def defineGlobalField(self, name: str) -> None: ...
    def getGlobalField(self) -> Any: ...

class ShipCompField:  # Partial stub
    def __init__(self, name: str = ..., field: Any = ...) -> None: ...

class ShipBellField:  # Partial stub
    def __init__(self, name: str, max_field: float, z: float, orient: int, halfHeight: float) -> None: ...

class ShipMCTrack(TParticle):  # Partial stub
    def GetPdgCode(self) -> int: ...
    def GetMotherId(self) -> int: ...
    def GetStartX(self) -> float: ...
    def GetStartY(self) -> float: ...
    def GetStartZ(self) -> float: ...
    def GetStartT(self) -> float: ...
    def GetP(self) -> float: ...
    def GetPt(self) -> float: ...
    def GetMass(self) -> float: ...
    def GetEnergy(self) -> float: ...
    def GetRapidity(self) -> float: ...
    def GetProcID(self) -> int: ...
    def GetNPoints(self, detId: int = ...) -> int: ...
    def IsSecondary(self) -> bool: ...
    def GetProcName(self) -> str: ...
    def LastMom(self) -> TVector3: ...

class ShipParticle(TParticle):  # Partial stub
    def __init__(
        self, pdg: int, status: int, mother1: int, mother2: int, t1: int, t2: int, p: TLorentzVector, v: TLorentzVector
    ) -> None: ...
    def GetMotherId(self) -> int: ...
    def GetDaughter(self, i: int) -> int: ...
    def GetDoca(self) -> float: ...
    def GetMass(self) -> float: ...
    def GetVertex(self, *args: Any) -> TVector3: ...
    def SetDoca(self, doca: float) -> None: ...
    def SetCovV(self, cov: Any) -> None: ...
    def SetCovP(self, cov: Any) -> None: ...

# --- Detectors ---

class strawtubes:  # Partial stub
    def __init__(self, medium: str = ...) -> None: ...
    def SetzPositions(self, z1: float, z2: float, z3: float, z4: float) -> None: ...
    def SetApertureArea(self, width: float, height: float) -> None: ...
    def SetStrawDiameter(self, outer: float, wall: float) -> None: ...
    def SetStrawPitch(self, pitch: float, y_offset: float) -> None: ...
    def SetDeltazLayer(self, dz: float) -> None: ...
    def SetStereoAngle(self, angle: float) -> None: ...
    def SetWireThickness(self, thickness: float) -> None: ...
    def SetDeltazView(self, dz: float) -> None: ...
    def SetFrameMaterial(self, material: str) -> None: ...
    def SetStationEnvelope(self, width: float, height: float, length: float) -> None: ...
    def SetStrawResolution(self, vdrift: float, sigma: float) -> None: ...
    def StrawVdrift(self) -> float: ...
    def StrawSigmaSpatial(self) -> float: ...
    def GetName(self) -> str: ...

class strawtubesHit(FairMCPoint):  # Partial stub
    def __init__(self, point: Any = ..., t0: float = ...) -> None: ...
    def GetDetectorID(self) -> int: ...
    def GetStationNumber(self) -> int: ...
    def GetXYZ(self) -> TVector3: ...
    def isValid(self) -> bool: ...
    def GetTDC(self) -> float: ...

class veto:  # Partial stub
    def __init__(self) -> None: ...
    def SetVesselDimensions(self, xstart: float, xend: float, ystart: float, yend: float, z0: float) -> None: ...
    def SetLiquidVeto(self, flag: int) -> None: ...
    def SetVesselStructure(
        self,
        innerSupport: float,
        sensitiveThickness: float,
        outerSupport: float,
        innerSupportMed: str,
        lidThickness: float,
        sensitiveMed: str,
        outerSupportMed: str,
        decayMed: str,
        rib: float,
    ) -> None: ...
    def GetName(self) -> str: ...

class vetoHit(FairMCPoint):  # Partial stub
    def __init__(self, point: Any = ..., t0: float = ...) -> None: ...
    def GetDetectorID(self) -> int: ...
    def GetXYZ(self) -> TVector3: ...
    def SetTDC(self, tdc: float) -> None: ...
    def setInvalid(self) -> None: ...

class vetoHitOnTrack:  # Partial stub
    def __init__(self, hitID: int, dist: float) -> None: ...

class splitcal:  # Partial stub
    def __init__(self, name: str, active: bool) -> None: ...
    def SetThickness(
        self,
        activeECAL: float,
        activeHCAL: float,
        filterECAL: float,
        filterECAL_first: float,
        filterHCAL: float,
        activeECAL_gas: float,
    ) -> None: ...
    def SetMaterial(self, activeECAL: int, activeHCAL: int, filterECAL: int, filterHCAL: int) -> None: ...
    def SetNSamplings(self, nECAL: int, nHCAL: int, activeHCAL: int) -> None: ...
    def SetZStart(self, z: float) -> None: ...
    def SetXMax(self, x: float) -> None: ...
    def SetYMax(self, y: float) -> None: ...
    def SetEmpty(
        self, empty: float, bigGap: float, gas_gap: float, first: int, second: int, third: int, num: int
    ) -> None: ...
    def SetNModules(self, nx: int, ny: int) -> None: ...
    def SetNStrips(self, n: int) -> None: ...
    def SetStripSize(self, halfWidth: float, halfLength: float) -> None: ...
    def GetName(self) -> str: ...

class splitcalHit(FairMCPoint):  # Partial stub
    def __init__(self, point: Any = ..., t0: float = ...) -> None: ...
    def GetDetectorID(self) -> int: ...

class splitcalCluster:  # Partial stub
    def AddHit(self, hit_index: int, weight: float) -> None: ...
    def SetIndex(self, idx: int) -> None: ...
    def ComputeEtaPhiE(self, det: Any) -> None: ...

class TimeDet:  # Partial stub
    def __init__(self, name: str, active: bool) -> None: ...
    def SetZposition(self, z: float) -> None: ...
    def SetBarZspacing(self, dzRow: float, dzCol: float) -> None: ...
    def SetBarZ(self, z: float) -> None: ...
    def SetSizeX(self, x: float) -> None: ...
    def SetSizeY(self, y: float) -> None: ...
    def GetName(self) -> str: ...

class TimeDetHit(FairMCPoint):  # Partial stub
    def __init__(self, point: Any = ..., t0: float = ...) -> None: ...
    def GetDetectorID(self) -> int: ...
    def isValid(self) -> bool: ...
    def GetMeasurements(self) -> Any: ...

class UpstreamTagger:  # Partial stub
    def __init__(self, name: str, active: bool) -> None: ...
    def SetZposition(self, z: float) -> None: ...
    def SetBoxDimensions(self, x: float, y: float, z: float) -> None: ...
    def GetName(self) -> str: ...

class UpstreamTaggerHit(FairMCPoint):  # Partial stub
    def __init__(self, point: Any = ..., t0: float = ..., pos_res: float = ..., time_res: float = ...) -> None: ...
    def GetDetectorID(self) -> int: ...

class MTCDetector:  # Partial stub
    def __init__(self, name: str, active: bool) -> None: ...
    def SetMTCParameters(
        self,
        width: float,
        height: float,
        angle: float,
        ironThick: float,
        sciFiThick: float,
        num_agg: int,
        scintThick: float,
        nLayers: float,
        zPosition: float,
        fieldY: float,
        gap: float = ...,
    ) -> None: ...
    def GetName(self) -> str: ...

class MTCDetHit(FairMCPoint):  # Partial stub
    def __init__(self, detID: int = ..., points: Any = ..., weights: Any = ...) -> None: ...
    def GetDetectorID(self) -> int: ...

class MTCHit(FairMCPoint):  # Partial stub
    def __init__(self, detID: int = ..., points: Any = ...) -> None: ...

class SiliconTarget:  # Partial stub
    def __init__(self, name: str, active: bool) -> None: ...
    def SetSiliconTargetParameters(
        self,
        width: float,
        height: float,
        sensorWidth: float,
        sensorLength: float,
        nLayers: int,
        zPosition: float,
        thickness: float,
        spacing: float,
        moduleOffset: float,
    ) -> None: ...
    def GetName(self) -> str: ...

class SiliconTargetHit(FairMCPoint):  # Partial stub
    def __init__(self, detID: int = ..., points: Any = ...) -> None: ...
    def GetDetectorID(self) -> int: ...

class Target:  # Partial stub
    def __init__(self, name: str, ydist: float, active: bool) -> None: ...
    def MakeNuTargetPassive(self, passive: int) -> None: ...
    def MergeTopBot(self, merge: int) -> None: ...
    def SetDetectorDesign(self, design: int) -> None: ...
    def SetCenterZ(self, z: float) -> None: ...
    def SetNumberBricks(self, col: int, row: int, wall: int) -> None: ...
    def SetDetectorDimension(self, x: float, y: float, z: float) -> None: ...
    def SetTargetWallDimension(self, x: float, y: float, z: float) -> None: ...
    def SetEmulsionParam(self, *args: float) -> None: ...
    def SetBrickParam(self, *args: float | int) -> None: ...
    def SetCellParam(self, z: float) -> None: ...
    def SetPillarDimension(self, x: float, y: float, z: float) -> None: ...
    def SetBaseDimension(self, x: float, y: float, z: float) -> None: ...
    def SetTTzdimension(self, z: float) -> None: ...
    def GetName(self) -> str: ...

class TargetTracker:  # Partial stub
    def __init__(self, name: str, x: float, y: float, z: float, active: bool) -> None: ...
    def SetDesign(self, design: int) -> None: ...
    def SetSciFiParam(
        self, width: float, x: float, y: float, z: float, support_z: float, honeycomb_z: float
    ) -> None: ...
    def SetNumberSciFi(self, nHor: int, nVert: int) -> None: ...
    def SetTargetTrackerParam(self, x: float, y: float, z: float) -> None: ...
    def SetBrickParam(self, z: float) -> None: ...
    def SetTotZDimension(self, z: float) -> None: ...
    def SetNumberTT(self, n: int) -> None: ...
    def GetName(self) -> str: ...

class exitHadronAbsorber:  # Partial stub
    def __init__(self) -> None: ...
    def GetName(self) -> str: ...
    def SetZposition(self, z: float) -> None: ...
    def SetEnergyCut(self, cut: float) -> None: ...
    def SetOnlyMuons(self, flag: bool = ...) -> None: ...
    def SkipNeutrinos(self, flag: bool = ...) -> None: ...
    def SetVetoPointName(self, name: str) -> None: ...
    def SetOpt4DP(self, flag: bool = ...) -> None: ...
    def SetUseCaveCoordinates(self, flag: bool = ...) -> None: ...
    def SetCylindricalPlane(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...

class Tracklet:  # Partial stub
    def __init__(self, track_type: int, indices: Any) -> None: ...
    def getType(self) -> int: ...
    def getList(self) -> Any: ...

class dataStruct:  # Partial stub
    x: float
    y: float
    z: float
    Bx: float
    By: float
    Bz: float

class rangeStruct:  # Partial stub
    xMin: float
    xMax: float
    yMin: float
    yMax: float
    zMin: float
    zMax: float
    dx: float
    dy: float
    dz: float

# --- Generators ---

class Pythia8Generator:  # Partial stub
    def __init__(self) -> None: ...
    def UseExternalFile(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def SetTargetCoordinates(self, z0: float, z1: float) -> None: ...
    def SetMom(self, mom: float) -> None: ...
    def GetMom(self) -> float: ...
    def SetSmearBeam(self, smear: float) -> None: ...
    def SetPaintRadius(self, radius: float) -> None: ...
    def SetEnergyCut(self, cut: float) -> None: ...
    def SetHeartBeat(self, n: int) -> None: ...
    def SetG4only(self) -> None: ...
    def SetZoffset(self, z: float) -> None: ...
    def SetParameters(self, params: str) -> None: ...
    def UseRandom3(self) -> None: ...
    def UseDeepCopy(self) -> None: ...
    def SetId(self, pdgid: int) -> None: ...
    def List(self, pdgid: int) -> None: ...
    def getPythiaInstance(self) -> Any: ...
    def nrOfRetries(self) -> int: ...

class HNLPythia8Generator(Pythia8Generator):  # Partial stub
    def __init__(self) -> None: ...
    def SetHNLId(self, pdgid: int) -> None: ...
    def SetLmin(self, lmin: float) -> None: ...
    def SetLmax(self, lmax: float) -> None: ...
    def nrOfDP(self) -> int: ...

class DPPythia8Generator(Pythia8Generator):  # Partial stub
    def __init__(self) -> None: ...
    def SetDPId(self, dpid: int) -> None: ...
    def GetDPId(self) -> int: ...
    def SetDY(self) -> None: ...
    def SetMinDPMass(self, mass: float) -> None: ...
    def MinDPMass(self) -> float: ...
    def SetPbrem(self, hist: TH2F) -> None: ...
    def SetLmin(self, lmin: float) -> None: ...
    def SetLmax(self, lmax: float) -> None: ...
    def nrOfRetries(self) -> int: ...
    def nrOfDP(self) -> int: ...

class FixedTargetGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def SetTargetCoordinates(self, z0: float, z1: float) -> None: ...
    def SetMom(self, mom: float) -> None: ...
    def SetSmearBeam(self, smear: float) -> None: ...
    def SetPaintRadius(self, radius: float) -> None: ...
    def SetEnergyCut(self, cut: float) -> None: ...
    def SetHeartBeat(self, n: int) -> None: ...
    def SetG4only(self) -> None: ...
    def SetZoffset(self, z: float) -> None: ...
    def SetSeed(self, seed: int) -> None: ...
    def SetBoost(self, boost: float) -> None: ...
    def SetDebug(self, debug: bool) -> None: ...
    def SetTauOnly(self) -> None: ...
    def SetJpsiMainly(self) -> None: ...
    def SetXoffset(self, x: float) -> None: ...
    def SetYoffset(self, y: float) -> None: ...
    def WithEvtGen(self) -> None: ...
    def InitForCharmOrBeauty(self, charm: str, nev: int, pot: float, nStart: int) -> None: ...
    def GetPythia(self) -> Any: ...
    def GetPotForCharm(self) -> float: ...
    def nrOfRetries(self) -> int: ...
    def nrOfDP(self) -> int: ...

class GenieGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def SetPositions(self, z_target: float, z_start: float, z_end: float) -> None: ...
    def GetNevents(self) -> int: ...
    def NuOnly(self) -> None: ...
    def MeanMaterialBudget(self, start: Any, end: Any, mparam: Any) -> None: ...

class MuDISGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def SetPositions(self, mu_start: float, mu_end: float) -> None: ...
    def GetNevents(self) -> int: ...

class MuonBackGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def GetNevents(self) -> int: ...
    def SetSmearBeam(self, smear: float) -> None: ...
    def SetPaintRadius(self, radius: float) -> None: ...
    def SetSameSeed(self, seed: int) -> None: ...
    def SetPhiRandomize(self, flag: bool) -> None: ...
    def SetDownScaleDiMuon(self, scale: float = ...) -> None: ...

class NtupleGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def GetNevents(self) -> int: ...

class EvtCalcGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, filename: str | list[str], firstEvent: int = ...) -> None: ...
    def SetPositions(self, zTa: float = ..., zDV: float = ...) -> None: ...
    def GetNevents(self) -> int: ...

class CosmicsGenerator:  # Partial stub
    def __init__(self) -> None: ...
    def Init(self, cosmic_file: str | int = ...) -> None: ...
    n_EVENTS: int

class tPythia6Generator:  # Partial stub
    def __init__(self) -> None: ...
    def SetMom(self, mom: float) -> None: ...
    def SetTarget(self, beam: str, target: str) -> None: ...
    def Pythia8(self) -> Any: ...
    def getPyint5_XSEC(self, i: int, j: int) -> float: ...

# ===========================================================================
# Geant4 classes (loaded dynamically, need static stubs)
# ===========================================================================

class G4ThreeVector:  # Partial stub
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...

class G4String:  # Partial stub
    def __init__(self, s: str) -> None: ...
    def c_str(self) -> str: ...

class G4RunManager:  # Partial stub
    @staticmethod
    def GetRunManager() -> G4RunManager: ...
    def GeometryHasBeenModified(self, prop: bool = ...) -> None: ...

class G4TransportationManager:  # Partial stub
    @staticmethod
    def GetTransportationManager() -> G4TransportationManager: ...
    def GetNavigatorForTracking(self) -> Any: ...

class G4FieldManager:  # Partial stub
    def __init__(self, field: G4UniformMagField = ...) -> None: ...
    def CreateChordFinder(self, field: G4UniformMagField) -> None: ...
    def GetDetectorField(self) -> Any: ...
    def DoesFieldExist(self) -> bool: ...

class G4UniformMagField:  # Partial stub
    def __init__(self, fieldVector: G4ThreeVector) -> None: ...
    def GetConstantFieldValue(self) -> G4ThreeVector: ...

class G4ParticleTable:  # Partial stub
    @staticmethod
    def GetParticleTable() -> G4ParticleTable: ...
    def FindParticle(self, name: str | int) -> Any: ...

class G4DecayTable:  # Partial stub
    def Insert(self, channel: G4PhaseSpaceDecayChannel) -> None: ...

class G4PhaseSpaceDecayChannel:  # Partial stub
    def __init__(self, parent: str, br: float, nDaughters: int, *daughters: str) -> None: ...

class G4EmParameters:  # Partial stub
    @staticmethod
    def Instance() -> G4EmParameters: ...
    def Dump(self) -> None: ...

class G4ProcessTable:  # Partial stub
    @staticmethod
    def GetProcessTable() -> G4ProcessTable: ...
    def FindProcess(self, name: str | G4String, particle: str | G4String = ...) -> Any: ...

class G4UIterminal:  # Partial stub
    def __init__(self) -> None: ...
    def SessionStart(self) -> None: ...

# --- Geant4 VMC classes ---

class TGeant4:  # Partial stub
    @staticmethod
    def GetMC() -> TGeant4: ...
    def ProcessGeantCommand(self, command: str) -> None: ...
    def ProcessGeantMacro(self, filename: str) -> None: ...

class TG4GeometryManager:  # Partial stub
    @staticmethod
    def Instance() -> TG4GeometryManager: ...
    def SetUserPostDetConstruction(self, fieldMaker: Any) -> None: ...
    def ConstructSDandField(self) -> None: ...

class TG4GeometryServices:  # Partial stub
    @staticmethod
    def Instance() -> TG4GeometryServices: ...
    def GetField(self, name: G4String, pos: Any, bf: Any) -> None: ...

class TVirtualMC:  # Partial stub
    @staticmethod
    def GetMC() -> TVirtualMC: ...
    def ProcessRun(self, nEvents: int) -> None: ...
    def GetStack(self) -> Any: ...

class TPythia6:  # Partial stub
    @staticmethod
    def Instance() -> TPythia6: ...
    def Initialize(self, frame: str, beam: str, target: str, energy: float) -> None: ...
    def GenerateEvent(self) -> None: ...
    def GetN(self) -> int: ...
    def GetK(self, i: int, j: int) -> int: ...
    def GetP(self, i: int, j: int) -> float: ...
    def GetV(self, i: int, j: int) -> float: ...
    def SetP(self, i: int, j: int, val: float) -> None: ...
    def SetMSEL(self, msel: int) -> None: ...
    def SetMSTU(self, i: int, val: int) -> None: ...
    def SetMDCY(self, kc: int, j: int, val: int) -> None: ...
    def SetPARP(self, i: int, val: float) -> None: ...
    def SetMRPY(self, i: int, val: int) -> None: ...
    def GetMSTI(self, i: int) -> int: ...
    def GetPARI(self, i: int) -> float: ...
    def Pycomp(self, pdg: int) -> int: ...
    def Pyedit(self, medit: int) -> None: ...
    def Pylist(self, mlist: int) -> None: ...
    def GetPARP(self, i: int) -> float: ...
    def GetMSTP(self, i: int) -> int: ...
    def SetMSTP(self, i: int, value: int) -> None: ...
    def SetPARJ(self, i: int, value: float) -> None: ...
    def SetMSTJ(self, i: int, value: int) -> None: ...
    def OpenFortranFile(self, lun: int, filename: str) -> None: ...

class TPythia8:  # Partial stub
    def Pythia8(self) -> Any: ...
    def Plist(self, pdgid: int) -> None: ...

# ---------------------------------------------------------------------------
# gMC global
# ---------------------------------------------------------------------------
gMC: TVirtualMC

# ---------------------------------------------------------------------------
# Additional GUI classes
# ---------------------------------------------------------------------------
class TGTextButton:  # Partial stub
    def __init__(self, parent: Any, text: str, id: int = ...) -> None: ...
    def SetWidth(self, width: int) -> None: ...
    def SetToolTipText(self, text: str, delay: int = ...) -> None: ...
    def SetCommand(self, command: str) -> None: ...

class TGVerticalFrame:  # Partial stub
    def __init__(self, parent: Any, w: int = ..., h: int = ...) -> None: ...
    def AddFrame(self, frame: Any, hints: TGLayoutHints = ...) -> None: ...
    def SetCleanup(self, mode: int) -> None: ...
    def SetWidth(self, width: int) -> None: ...

class TGLayoutHints:  # Partial stub
    def __init__(
        self, hints: int = ..., padleft: int = ..., padright: int = ..., padtop: int = ..., padbottom: int = ...
    ) -> None: ...

class TGString:  # Partial stub
    def __init__(self, s: str) -> None: ...

class TGLVertex3:  # Partial stub
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...

class TGLFont:  # Partial stub
    kExtrude: int

class TGLCameraOverlay:  # Partial stub
    kAll: int

class TObjArray(TObject):  # Partial stub
    def __init__(self, size: int = ...) -> None: ...
    def At(self, idx: int) -> TObject: ...
    def GetEntries(self) -> int: ...
    def Add(self, obj: TObject) -> None: ...
    def Clear(self, option: str = ...) -> None: ...
    def __getitem__(self, idx: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

# Re-export vector at module level (some code uses ROOT.vector)
vector = std.vector

# basiclibs compatibility module
def basiclibs() -> None: ...

# ---------------------------------------------------------------------------
# RNTuple support (ROOT 7)
# ---------------------------------------------------------------------------
class ROOT:  # Partial stub — for ROOT.ROOT.RNTupleReader
    class RNTupleReader:  # Partial stub
        @staticmethod
        def Open(name: str, filename: str) -> Any: ...

    class Experimental:  # Partial stub
        class RNTupleReader:  # Partial stub
            @staticmethod
            def Open(name: str, filename: str) -> Any: ...

        class RNTupleImporter:  # Partial stub
            @staticmethod
            def Create(src: str, dst: str, name: str = ...) -> Any: ...
