# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
# https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
body = """
{%- macro remote_url() -%}
  https://github.com/ShipSoft/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro print_commit(commit) -%}
    - {% if commit.scope %}(*{{ commit.scope }}*) {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
      {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}\
      {% if commit.remote.pr_number %} from [!{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pulls/{{ commit.remote.pr_number }}){%- endif %} \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{%- endmacro -%}

{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% if message and message != version %}
    {{ message | trim | upper_first }}
{% endif %}\
{% if previous %}\
    {% if previous.commit_id and commit_id %}
        This version contains [{{ previous.commit_id | truncate(length=7, end="") }}...\
            {{ commit_id | truncate(length=7, end="") }}]\
            ({{ self::remote_url() }}/compare/{{ previous.commit_id }}...{{ commit_id }}).
    {% endif %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="breaking")
    | reverse
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits
        | filter(attribute="breaking", value=true)
        | sort(attribute="breaking")
        | reverse %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
    {% for commit in commits %}
        {%- if not commit.scope and not commit.breaking -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
{%- set first_time_contributors = github.contributors | filter(attribute="is_first_time", value=true) -%}
{%- if first_time_contributors | length > 0 %}
### New contributors
    {% for contributor in first_time_contributors %}
        - @{{ contributor.username }} made their first contribution{% if contributor.pr_number %} in #{{ contributor.pr_number }}{% endif %}
    {%- endfor %}\n
{%- endif %}\n
### Statistics\n
- {{ statistics.commit_count }} commit(s) contributed to the release.
- {{ statistics.links | length }} linked issue(s) detected in commits.
{%- if statistics.links | length > 0 %}
    {%- for link in statistics.links %}
        {{ "  " }}- [{{ link.text }}]({{ link.href }}) (referenced {{ link.count }} time(s))
    {%- endfor %}
{%- endif %}
{%- if statistics.days_passed_since_last_release %}
    - {{ statistics.days_passed_since_last_release }} day(s) passed between releases.
{%- endif %}\n\n
"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[git]
# Limit to wanted release tags with this
tag_pattern = "(\\d{2}\\.\\d{2}|v\\d-\\d{2}|ECN3_\\d{4})"

# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
commit_preprocessors = [
    # Fix breaking ! place before the scope (per-spec should be placed after)
    { pattern = "^(\\w+)!\\(([^\\)]+)\\):", replace = "$1($2)!:"},
    # Change <type>(style): to just be style:
    { pattern = "^(\\w+)\\(style\\):", replace = "style:"},
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    { message = "^feat", group = "<!-- 1 --> Features" },
    { message = "^fix", group = "<!-- 2 --> Bug Fixes" },
    { message = "^doc", group = "<!-- 6 --> Documentation" },
    { message = "^perf", group = "<!-- 3 --> Performance" },
    { message = "^refactor", group = "<!-- 4 --> Refactor" },
    # If we want to show styling commits we could enable this group
    #{ message = "^style", group = "<!-- 7 --> Styling" },
    { message = "^style", skip = true },
    { message = "^test", group = "<!-- 5 --> Testing" },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(pre-commit\\)", skip = true },
    { message = "^\\[pre-commit\\.ci\\]", skip = true },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore|^ci", group = "<!-- 8 --> Miscellaneous Tasks" },
    { body = ".*security", group = "<!-- 0 --> Security" },

    # Custom matchers to make changelog for unconventional commits a bit nicer
    { message = "^[a|A]dd", group = "<!-- 1 --> Features" },
    { message = "^[r|R]emove", group = "<!-- 2 --> Bug Fixes" },
    { message = "^[f|F]ix", group = "<!-- 2 --> Bug Fixes" },
    { message = "^[i|I]mprove", group = "<!-- 4 --> Refactor" },
    { message = "^[c|C]lean", group = "<!-- 4 --> Refactor" },
    { message = "^[m|M]ove", group = "<!-- 4 --> Refactor" },
    { message = "^[r|R]e(name|structure)", group = "<!-- 4 --> Refactor" },
    { message = "^.*", group = "<!-- 8 --> Miscellaneous Tasks" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"

# Enabling more info from GitHub requires a GitHub token when generating, or
# we hit rate-limiting.
#[remote.github]
#owner = "ShipSoft"
#repo = "FairShip"
