var index =
[
    [ "Major changes", "changes_page.html", [
      [ "Solution methods", "changes_page.html#ch-methods", [
        [ "Inversion", "changes_page.html#ch-inv", null ],
        [ "Diagonalization", "changes_page.html#ch-diag", null ],
        [ "Minimal Residual Method (MINRES)", "changes_page.html#ch-minres", null ],
        [ "Advanced Minimal Residual Method (MINRES-QLP)", "changes_page.html#ch-minresqlp", null ],
        [ "Elimination of constraints", "changes_page.html#ch-elim-const", null ]
      ] ],
      [ "Regularization", "changes_page.html#ch-regul", null ],
      [ "Local fit", "changes_page.html#ch-locfit", null ],
      [ "Parallelization", "changes_page.html#ch-openmp", null ],
      [ "Compressed sparse matrix", "changes_page.html#ch-compression", null ],
      [ "Gzipped C binary files", "changes_page.html#ch-gzip", null ],
      [ "Transformation from FORTRAN77 to Fortran90", "changes_page.html#ch-transf", null ],
      [ "Memory management", "changes_page.html#ch-memmanage", null ],
      [ "Read buffer size", "changes_page.html#ch-readbuf", null ],
      [ "Number of binary files", "changes_page.html#ch-numbin", null ]
    ] ],
    [ "List of options and commands", "option_page.html", [
      [ "Command line options:", "option_page.html#sec-opt", [
        [ "-t", "option_page.html#opt-t1", null ],
        [ "-t=track-model", "option_page.html#opt-t2", null ],
        [ "-s", "option_page.html#opt-s", null ],
        [ "-f", "option_page.html#opt-f", null ],
        [ "-c", "option_page.html#opt-c", null ],
        [ "-C", "option_page.html#opt-C", null ]
      ] ],
      [ "Steering file commands:", "option_page.html#sec-cmd", [
        [ "bandwidth", "option_page.html#cmd-bandwidth", null ],
        [ "cache", "option_page.html#cmd-cache", null ],
        [ "Cfiles", "option_page.html#cmd-cfiles", null ],
        [ "checkinput", "option_page.html#cmd-checkinput", null ],
        [ "chisqcut", "option_page.html#cmd-chisqcut", null ],
        [ "compress", "option_page.html#cmd-compress", null ],
        [ "closeandreopen", "option_page.html#cmd-closeandreopen", null ],
        [ "constraint", "option_page.html#cmd-constraint", null ],
        [ "debug", "option_page.html#cmd-debug", null ],
        [ "dwfractioncut", "option_page.html#cmd-dwfractioncut", null ],
        [ "entries", "option_page.html#cmd-entries", null ],
        [ "errlabels", "option_page.html#cmd-errlabels", null ],
        [ "force", "option_page.html#cmd-force", null ],
        [ "fortranfiles", "option_page.html#cmd-fortranfiles", null ],
        [ "globalcorr", "option_page.html#cmd-globalcorr", null ],
        [ "histprint", "option_page.html#cmd-histprint", null ],
        [ "hugecut", "option_page.html#cmd-hugecut", null ],
        [ "iterateentries", "option_page.html#cmd-iterateentries", null ],
        [ "linesearch", "option_page.html#cmd-linesearch", null ],
        [ "localfit", "option_page.html#cmd-localfit", null ],
        [ "matiter", "option_page.html#cmd-matiter", null ],
        [ "matmoni", "option_page.html#cmd-matmoni", null ],
        [ "maxrecord", "option_page.html#cmd-maxrecord", null ],
        [ "measurement", "option_page.html#cmd-measurement", null ],
        [ "memorydebug", "option_page.html#cmd-memorydebug", null ],
        [ "method", "option_page.html#cmd-method", null ],
        [ "monitorresiduals", "option_page.html#cmd-monres", null ],
        [ "monitorpulls", "option_page.html#cmd-monpull", null ],
        [ "mresmode", "option_page.html#cmd-mresmode", null ],
        [ "mrestranscond", "option_page.html#cmd-mrestranscond", null ],
        [ "mrestol", "option_page.html#cmd-mrestol", null ],
        [ "nofeasiblestart", "option_page.html#cmd-nofeasiblestart", null ],
        [ "outlierdownweighting", "option_page.html#cmd-outlierdownweighting", null ],
        [ "pairentries", "option_page.html#cmd-pairentries", null ],
        [ "parameter", "option_page.html#cmd-parameter", null ],
        [ "presigma", "option_page.html#cmd-presigma", null ],
        [ "print", "option_page.html#cmd-print", null ],
        [ "printcounts", "option_page.html#cmd-printcounts", null ],
        [ "printrecord", "option_page.html#cmd-printrecord", null ],
        [ "pullrange", "option_page.html#cmd-pullrange", null ],
        [ "regularisation", "option_page.html#cmd-regularisation", null ],
        [ "regularization", "option_page.html#cmd-regularization", null ],
        [ "scaleerrors", "option_page.html#cmd-scaleerrors", null ],
        [ "skipemptycons", "option_page.html#cmd-skipemptycons", null ],
        [ "subito", "option_page.html#cmd-subito", null ],
        [ "threads", "option_page.html#cmd-threads", null ],
        [ "weightedcons", "option_page.html#cmd-weightedcons", null ],
        [ "withelimination", "option_page.html#cmd-withelim", null ],
        [ "withmultipliers", "option_page.html#cmd-withmult", null ],
        [ "wolfe", "option_page.html#cmd-wolfe", null ]
      ] ]
    ] ],
    [ "List of exit codes", "exit_code_page.html", null ]
];