#!/usr/bin/python3
from ROOT import TFile, TCanvas, TLegend, TPaveLabel, TH1F
import os

ff = TFile.Open("FullFieldData/MC-ComparisonChi2mu_linP.root","read")
cf = ff.Get("output")
hfd = cf.GetPrimitive("linp/ptmu_x")
fi = TFile.Open("plots/inter-MC-ComparisonChi2mu_linP.root","read")
ci = fi.Get("c")
hfm = cf.GetPrimitive("linMCp/ptmu_x")
hfc = cf.GetPrimitive("linMCp/ptmucharm_x")
hfp = cf.GetPrimitive("linMCp/ptmuDi-muon P8_x")
hfg = cf.GetPrimitive("linMCp/ptmuHadronic inelastic_x")
hfl = cf.GetPrimitive("linMCp/ptmuLepton pair_x")
hfe = cf.GetPrimitive("linMCp/ptmuPositron annihilation_x")
hfm2 = cf.GetPrimitive("linMC10p/ptmu_x")
hfc2 = cf.GetPrimitive("linMC10p/ptmucharm_x")
hfp2 = cf.GetPrimitive("linMC10p/ptmuDi-muon P8_x")
hfg2 = cf.GetPrimitive("linMC10p/ptmuHadronic inelastic_x")
hfl2 = cf.GetPrimitive("linMC10p/ptmuLepton pair_x")
hfe2 = cf.GetPrimitive("linMC10p/ptmuPositron annihilation_x")
hid = ci.GetPrimitive("inter/hpd")
him = ci.GetPrimitive("inter/hpM")
hic = ci.GetPrimitive("inter/hpc")
hip = ci.GetPrimitive("inter/hp7")
hig = ci.GetPrimitive("inter/hp2")
hil = ci.GetPrimitive("inter/hp3")
hie = ci.GetPrimitive("inter/hp4")

os.mkdir('plots2')

legendd = TLegend(0.55,0.8,0.9,0.9)
legendd.AddEntry(hfd,"full field","lp")
legendd.AddEntry(hid,"intermediate field","lp")

cd = TCanvas("canvas Data")
hid.SetNameTitle("inter/hpd","Momentum distribution from data")
hfd.SetNameTitle("full/hpd","Momentum distribution from data")
hfd.SetLineColor(2)
hid.Draw("h")
hfd.Draw("h same")
legendd.Draw()
cd.Print("plots2/Data.pdf")

fo = TFile.Open("plots2/Data.root","RECREATE")
cd.Write()
fo.Close()

hfm.SetLineColor(632+2)
hfc.SetLineColor(632-4)
hfp.SetLineColor(632-3)
hfg.SetLineColor(632-7)
hfl.SetLineColor(632-6)
hfe.SetLineColor(632-9)
hfm2.SetLineColor(632+2)
hfc2.SetLineColor(632-4)
hfp2.SetLineColor(632-3)
hfg2.SetLineColor(632-7)
hfl2.SetLineColor(632-6)
hfe2.SetLineColor(632-9)
him.SetLineColor(600+2)
hic.SetLineColor(600-4)
hip.SetLineColor(600-3)
hig.SetLineColor(600-7)
hil.SetLineColor(600-6)
hie.SetLineColor(600-9)

legendm = TLegend(0.55,0.5,0.9,0.9)
legendm.AddEntry(hfm,"full: MC inclusive","lp")
legendm.AddEntry(hfc,"full: Charm","lp")
legendm.AddEntry(hfp,"full: Dimuon from decays P8","lp")
legendm.AddEntry(hfg,"full: Dimuon from decays G4","lp")
legendm.AddEntry(hfl,"full: Photon conversion","lp")
legendm.AddEntry(hfe,"full: Positron annihilation","lp")
legendm.AddEntry(him,"inter: MC inclusive","lp")
legendm.AddEntry(hic,"inter: Charm","lp")
legendm.AddEntry(hip,"inter: Dimuon from decays P8","lp")
legendm.AddEntry(hig,"inter: Dimuon from decays G4","lp")
legendm.AddEntry(hil,"inter: Photon conversion","lp")
legendm.AddEntry(hie,"inter: Positron annihilation","lp")

hfm.SetNameTitle("full/hpm","Momentum distribution from MC")
hfc.SetName("full/hpc")
hfp.SetName("full/hp7")
hfg.SetName("full/hp2")
hfl.SetName("full/hp3")
hfe.SetName("full/hp4")
him.SetNameTitle("inter/hpm","Momentum distribution from MC")
hic.SetName("inter/hpc")
hip.SetName("inter/hp7")
hig.SetName("inter/hp2")
hil.SetName("inter/hp3")
hie.SetName("inter/hp4")
hfm2.SetName("full/hpm-10GeV")

cm = TCanvas("canvas MC")
him.SetAxisRange(5,120-0.5,"X")
him.GetXaxis().SetTitle("P [GeV/c]")
him.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
him.SetStats(0)
him.Draw()
hic.Draw("same")
hip.Draw("same")
hig.Draw("same")
hil.Draw("same")
hie.Draw("same")
hfm.Draw("same")
hfc.Draw("same")
hfp.Draw("same")
hfg.Draw("same")
hfl.Draw("same")
hfe.Draw("same")
hfm2.Draw("same")
hfc2.Draw("same")
hfp2.Draw("same")
hfg2.Draw("same")
hfl2.Draw("same")
hfe2.Draw("same")
legendm.Draw()
cm.Print("plots2/MC.pdf")

fo = TFile.Open("plots2/MC.root","RECREATE")
cm.Write()
fo.Close()

legendm2 = TLegend(0.55,0.75,0.9,0.9)
legendm2.AddEntry(hfm,"full: MC inclusive","lp")
legendm.AddEntry(him,"inter: MC inclusive","lp")

cm2 = TCanvas("canvas MCpure")
him.SetStats(0)
him.Draw()
hfm.Draw("same")
hfm2.Draw("same")
cm2.Print("plots2/MCpure.pdf")

fo = TFile.Open("plots2/MCpure.root","RECREATE")
cm2.Write()
fo.Close()

cc = TCanvas("canvas Charm")
hfc.SetAxisRange(5,120-0.5,"X")
hfc.GetXaxis().SetTitle("P [GeV/c]")
hfc.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
hfc.SetMaximum(4.5e-6)
hfc.SetNameTitle("full/hic","Momentum distribution from charm")
hfc.Draw()
hic.Draw("same")
hfc2.Draw("same")
legendc = TLegend(0.55,0.8,0.9,0.9)
legendc.AddEntry(hfc,"full field","lp")
legendc.AddEntry(hic,"intermediate field","lp")
legendc.Draw()
cc.Print("plots/Charm.pdf")

fo = TFile.Open("plots2/Charm.root","RECREATE")
cc.Write()
fo.Close()

cp = TCanvas("canvas P8")
hfp.SetAxisRange(5,120-0.5,"X")
hfp.GetXaxis().SetTitle("P [GeV/c]")
hfp.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
hfp.SetMaximum(1.4e-6)
hfp.SetNameTitle("full/hip","Momentum distribution from Pythia8 dimuon decay")
hfp.Draw()
hip.Draw("same")
hfp2.Draw("same")
legendp = TLegend(0.55,0.8,0.9,0.9)
legendp.AddEntry(hfp,"full field","lp")
legendp.AddEntry(hip,"intermediate field","lp")
legendp.Draw()
cp.Print("plots2/P8.pdf")

fo = TFile.Open("plots2/P8.root","RECREATE")
cp.Write()
fo.Close()

cg = TCanvas("canvas G4")
hfg.SetAxisRange(5,120-0.5,"X")
hfg.GetXaxis().SetTitle("P [GeV/c]")
hfg.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
hfg.SetMaximum(1.4e-6)
hfg.SetNameTitle("full/hig","Momentum distribution from Geant4 dimuon decay")
hfg.Draw()
hig.Draw("same")
hfg2.Draw("same")
legendg = TLegend(0.55,0.8,0.9,0.9)
legendg.AddEntry(hfg,"full field","lp")
legendg.AddEntry(hig,"intermediate field","lp")
legendg.Draw()
cg.Print("plots2/G4.pdf")

fo = TFile.Open("plots2/G4.root","RECREATE")
cg.Write()
fo.Close()

cl = TCanvas("canvas photon")
hfl.SetAxisRange(5,120-0.5,"X")
hfl.GetXaxis().SetTitle("P [GeV/c]")
hfl.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
hfl.SetMaximum(1.3e-6)
hfl.SetNameTitle("full/hil","Momentum distribution from photon conversion")
hfl.Draw()
hil.Draw("same")
hfl2.Draw("same")
legendl = TLegend(0.55,0.8,0.9,0.9)
legendl.AddEntry(hfl,"full field","lp")
legendl.AddEntry(hil,"intermediate field","lp")
legendl.Draw()
cl.Print("plots2/PhotonConversion.pdf")

fo = TFile.Open("plots2/PhotonConversion.root","RECREATE")
cl.Write()
fo.Close()

ce = TCanvas("canvas positron")
hfe.SetAxisRange(5,120-0.5,"X")
hfe.GetXaxis().SetTitle("P [GeV/c]")
hfe.GetYaxis().SetTitle("N [/(GeV/c)/PoT]")
hfe.SetMaximum(1.6e-8)
hfe.SetNameTitle("full/hie","Momentum distribution from positron annihilation")
hfe.Draw()
hie.Draw("same")
hfe2.Draw("same")
legende = TLegend(0.55,0.8,0.9,0.9)
legende.AddEntry(hfe,"full field","lp")
legende.AddEntry(hie,"intermediate field","lp")
legende.Draw()
ce.Print("plots2/PositronAnnihilation.pdf")

fo = TFile.Open("plots2/PositronAnnihilation.root","RECREATE")
ce.Write()
fo.Close()
