from typing import Any

def defaultLogging(logLevel: Any = ...) -> Any: ...

class Sequencer:
    def __init__(self, *, events: int = ..., numThreads: int = ..., trackFpes: bool = ..., **kwargs: Any) -> None: ...
    config: Any
    def addReader(self, reader: Any) -> None: ...
    def addAlgorithm(self, algorithm: Any) -> None: ...
    def addWriter(self, writer: Any) -> None: ...
    def addWhiteboardAlias(self, alias: str, original: str) -> None: ...
    def run(self) -> None: ...

class RandomNumbers:
    def __init__(self, *, seed: int = ..., **kwargs: Any) -> None: ...

class SiTargetBuilder:
    def __init__(self, **kwargs: Any) -> None: ...
    def trackingGeometry(self) -> Any: ...

class MTCBuilder:
    def __init__(self, **kwargs: Any) -> None: ...
    def trackingGeometry(self) -> Any: ...

class MagneticFieldMapXyz:
    def __init__(self, **kwargs: Any) -> None: ...

class StrawtubeBuilder:
    def __init__(self, **kwargs: Any) -> None: ...
    def trackingGeometry(self) -> Any: ...

class RootParticleReader:
    def __init__(self, **kwargs: Any) -> None: ...

class RootSimHitReader:
    def __init__(self, **kwargs: Any) -> None: ...

class TrackSelectorAlgorithm:
    def __init__(self, **kwargs: Any) -> None: ...

class SHiPTrackWriter:
    def __init__(self, **kwargs: Any) -> None: ...

class RootVertexReader:
    def __init__(self, **kwargs: Any) -> None: ...

class RootTrackStatesWriter:
    def __init__(self, **kwargs: Any) -> None: ...

class TrackFitterPerformanceWriter:
    def __init__(self, **kwargs: Any) -> None: ...

class RootTrackSummaryWriter:
    def __init__(self, **kwargs: Any) -> None: ...
