"""Partial type stubs for ROOT.Math as used in FairShip."""

from __future__ import annotations

from typing import Any

class GaussIntegrator:  # Partial stub
    def __init__(self) -> None: ...
    def SetFunction(self, f: WrappedTF1) -> None: ...
    def SetRelTolerance(self, tol: float) -> None: ...
    def Integral(self, low: float, high: float) -> float: ...

class Interpolator:  # Partial stub
    def __init__(self, x: Any, y: Any, itype: Any = ...) -> None: ...
    def Eval(self, x: float) -> float: ...
    def SetData(self, x: Any, y: Any) -> None: ...

class Interpolation:  # Partial stub
    kLINEAR: int
    kCSPLINE: int

class WrappedTF1:  # Partial stub
    def __init__(self, tf1: Any) -> None: ...

class LorentzVector:  # Partial stub
    """ROOT::Math::LorentzVector — instantiated via LorentzVector("coord_system")()."""

    def __init__(self, coord_system: str) -> None: ...
    def __call__(self, px: float, py: float, pz: float, E: float) -> LorentzVector: ...
    def Px(self) -> float: ...
    def Py(self) -> float: ...
    def Pz(self) -> float: ...
    def E(self) -> float: ...
    def Pt(self) -> float: ...
    def M(self) -> float: ...
    def M2(self) -> float: ...
    def P(self) -> float: ...
    def Eta(self) -> float: ...
    def Phi(self) -> float: ...
