from typing import Any

class ParticleSelectorConfig:
    def __init__(self, **kwargs: Any) -> None: ...

def addDigiParticleSelection(*args: Any, **kwargs: Any) -> None: ...
def addDigitization(*args: Any, **kwargs: Any) -> None: ...
