# Geometry configuration of SST (strawtubes) in FairShip

SST:
  width: 200                   # Aperture width (x) in cm (half length)
  height: 300                  # Aperture height (y) in cm (half length)
  wire_thickness: 0.003        # Sense wire thickness in cm
  wall_thickness: 0.0036       # Straw wall thickness in cm
  outer_straw_diameter: 2      # in cm
  straw_pitch: 2               # Distance (y) between straws in a layer in cm
  y_layer_offset: 1            # Offset (y) of straws between layers in cm
  delta_z_layer: 1.732         # Distance (z) between layers in cm
  delta_z_view: 12             # Distance (z) between stereo views in cm
  view_angle: 4.57             # Stereo angle in degree
  station_width: 300           # (x) in cm (half length)
  station_height: 350          # (y) in cm (half length)
  station_length: 50           # (z) in cm (half length)
