"""Type stubs for ROOT.std (partial — covers FairShip usage only)."""

from collections.abc import Iterator
from typing import Any

class vector:  # Partial stub
    """std::vector<T> — instantiated via vector("type_name")()."""

    def __init__(self, type_name: str | type | vector) -> None: ...
    def __call__(self, src: Any = ...) -> vector: ...
    def push_back(self, item: Any) -> None: ...
    def clear(self) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, index: int) -> Any: ...

class string:  # Partial stub
    """std::string wrapper."""

    def __init__(self, value: str = ...) -> None: ...
    def c_str(self) -> str: ...

def swap(a: Any, b: Any) -> None: ...
