#!/usr/bin/python3
# Usage: python3 addHistos.py
from ROOT import TList, TFile, TH1F, TH2F
import os, sys, subprocess

hpptList = TList()
hpList = TList()
hptList = TList()
hppt2List = TList()
hp2List = TList()
hpt2List = TList()
hppt3List = TList()
hp3List = TList()
hpt3List = TList()
hppt4List = TList()
hp4List = TList()
hpt4List = TList()
hppt7List = TList()
hp7List = TList()
hpt7List = TList()

def mergeHistos():
  global hpptList, hpList, hptList
  hppt = TH2F("hppt","Momentum distribution",300,0,300,40,0,4)
  hp = TH1F("hp","Momentum distribution",300,0,300)
  hpt = TH1F("hpt","Transverse momentum distribution",40,0,4)
  hppt2 = TH2F("hppt2","Momentum distribution",300,0,300,40,0,4)
  hp2 = TH1F("hp2","Momentum distribution",300,0,300)
  hpt2 = TH1F("hpt2","Transverse momentum distribution",40,0,4)
  hppt3 = TH2F("hppt3","Momentum distribution",300,0,300,40,0,4)
  hp3 = TH1F("hp3","Momentum distribution",300,0,300)
  hpt3 = TH1F("hpt3","Transverse momentum distribution",40,0,4)
  hppt4 = TH2F("hppt4","Momentum distribution",300,0,300,40,0,4)
  hp4 = TH1F("hp4","Momentum distribution",300,0,300)
  hpt4 = TH1F("hpt4","Transverse momentum distribution",40,0,4)
  hppt7 = TH2F("hppt7","Momentum distribution",300,0,300,40,0,4)
  hp7 = TH1F("hp7","Momentum distribution",300,0,300)
  hpt7 = TH1F("hpt7","Transverse momentum distribution",40,0,4)
  hppt.Merge(hpptList)
  hp.Merge(hpList)
  hpt.Merge(hptList)
  hppt2.Merge(hppt2List)
  hp2.Merge(hp2List)
  hpt2.Merge(hpt2List)
  hppt3.Merge(hppt3List)
  hp3.Merge(hp3List)
  hpt3.Merge(hpt3List)
  hppt4.Merge(hppt4List)
  hp4.Merge(hp4List)
  hpt4.Merge(hpt4List)
  hppt7.Merge(hppt7List)
  hp7.Merge(hp7List)
  hpt7.Merge(hpt7List)
  hppt.Write()
  hp.Write()
  hpt.Write()
  hppt2.Write()
  hp2.Write()
  hpt2.Write()
  hppt3.Write()
  hp3.Write()
  hpt3.Write()
  hppt4.Write()
  hp4.Write()
  hpt4.Write()
  hppt7.Write()
  hp7.Write()
  hpt7.Write()
  
def makeTotalHisto():
  outFile = TFile.Open("output/histo-intermediate-mbias-nocharm.root","RECREATE")
  mergeHistos()
  outFile.Close()

TotalGoodEventCount = 0
for XXXXX in range(0,20000,1000):
  for Y in range(5):
    fpath = "output/histo-XXXXX-Y.root".replace("XXXXX",str(XXXXX)).replace("Y",str(Y))
    fr = TFile.Open(fpath,"read")
    hppttemp = fr.Get("hppt")
    hppttemp.SetDirectory(0)
    hpptList.Add(hppttemp)
    hptemp = fr.Get("hp")
    hptemp.SetDirectory(0)
    hpList.Add(hptemp)
    hpttemp = fr.Get("hpt")
    hpttemp.SetDirectory(0)
    hptList.Add(hpttemp)
    hppt2temp = fr.Get("hppt2")
    hppt2temp.SetDirectory(0)
    hppt2List.Add(hppt2temp)
    hp2temp = fr.Get("hp2")
    hp2temp.SetDirectory(0)
    hp2List.Add(hp2temp)
    hpt2temp = fr.Get("hpt2")
    hpt2temp.SetDirectory(0)
    hpt2List.Add(hpt2temp)
    hppt3temp = fr.Get("hppt3")
    hppt3temp.SetDirectory(0)
    hppt3List.Add(hppt3temp)
    hp3temp = fr.Get("hp3")
    hp3temp.SetDirectory(0)
    hp3List.Add(hp3temp)
    hpt3temp = fr.Get("hpt3")
    hpt3temp.SetDirectory(0)
    hpt3List.Add(hpt3temp)
    hppt4temp = fr.Get("hppt4")
    hppt4temp.SetDirectory(0)
    hppt4List.Add(hppt4temp)
    hp4temp = fr.Get("hp4")
    hp4temp.SetDirectory(0)
    hp4List.Add(hp4temp)
    hpt4temp = fr.Get("hpt4")
    hpt4temp.SetDirectory(0)
    hpt4List.Add(hpt4temp)
    hppt7temp = fr.Get("hppt7")
    hppt7temp.SetDirectory(0)
    hppt7List.Add(hppt7temp)
    hp7temp = fr.Get("hp7")
    hp7temp.SetDirectory(0)
    hp7List.Add(hp7temp)
    hpt7temp = fr.Get("hpt7")
    hpt7temp.SetDirectory(0)
    hpt7List.Add(hpt7temp)
    fr.Close()

makeTotalHisto()
