[project]
name = "fairship"
version = "0.1.0"
description = ""
#readme = "README.md"
authors = []
requires-python = ">=3.6"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=7.0.1",
]
