export DEFAULTS_RELEASE_ROOT=/pool/condor/dir_55582/SHiPBuild/FairShip/sw/slc7_x86-64/defaults-release/v1-1
export DEFAULTS_RELEASE_VERSION=v1
export DEFAULTS_RELEASE_REVISION=1
export DEFAULTS_RELEASE_HASH=399356a4e5c7bc2f4d66039426b2db344b37bcd0
export DEFAULTS_RELEASE_COMMIT=0
export CXXFLAGS="-fPIC -g -O2 -std=c++11"
export CFLAGS="-fPIC -g -O2"
export CMAKE_BUILD_TYPE="RELEASE"
export DYLD_LIBRARY_PATH=$DEFAULTS_RELEASE_ROOT/lib:$DYLD_LIBRARY_PATH
export PATH=$DEFAULTS_RELEASE_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$DEFAULTS_RELEASE_ROOT/lib:$LD_LIBRARY_PATH
