from __future__ import annotations

from typing import Any, Self, overload

# Type aliases for ROOT types referenced from parent module
TVector3 = Any
TMatrixDSym = Any
TVectorD = Any

class TGeoMaterialInterface:
    # Partial stub
    def __init__(self) -> None: ...

class FairShipFields:
    # Partial stub
    def __init__(self) -> None: ...
    def setField(self, field: Any) -> None: ...

class BellField:
    # Partial stub
    def __init__(
        self,
        max: float,
        z: float,
        type: int,
        halfHeight: float,
    ) -> None: ...

class FieldManager:
    # Partial stub
    @staticmethod
    def getInstance() -> FieldManager: ...
    def init(self, bfield: Any) -> None: ...

class MaterialEffects:
    # Partial stub
    @staticmethod
    def getInstance() -> MaterialEffects: ...
    def init(self, geoMat: TGeoMaterialInterface) -> None: ...

class MeasurementOnPlane:
    # Partial stub
    def getState(self) -> TVectorD: ...
    def getCov(self) -> TMatrixDSym: ...

class MeasuredStateOnPlane:
    # Partial stub
    def __init__(self, rep: RKTrackRep) -> None: ...
    def getPos(self) -> TVector3: ...
    def getMom(self) -> TVector3: ...
    def getDir(self) -> TVector3: ...
    def getState(self) -> TVectorD: ...
    def getCov(self) -> TMatrixDSym: ...
    def getPDG(self) -> int: ...
    def getMomMag(self) -> float: ...
    def get6DCov(self) -> TMatrixDSym: ...
    def getCharge(self) -> float: ...
    def extrapolateToPlane(self, plane: SharedPlanePtr) -> float: ...

class StateOnPlane:
    # Partial stub
    def __init__(self, rep: RKTrackRep) -> None: ...
    def getPos(self) -> TVector3: ...
    def getMom(self) -> TVector3: ...

class RKTrackRep:
    # Partial stub
    def __init__(self, pdg: int) -> None: ...
    def setPosMomCov(
        self,
        state: MeasuredStateOnPlane,
        pos: TVector3,
        mom: TVector3,
        cov: TMatrixDSym,
    ) -> None: ...
    def get6DStateCov(
        self,
        state: MeasuredStateOnPlane,
        seedState: TVectorD,
        seedCov: TMatrixDSym,
    ) -> None: ...
    def setPosMom(
        self,
        state: StateOnPlane,
        pos: TVector3,
        mom: TVector3,
    ) -> None: ...
    def getPos(self, state: StateOnPlane) -> TVector3: ...
    def extrapolateToPoint(
        self,
        state: StateOnPlane,
        point: TVector3,
        stopAtBoundary: bool,
    ) -> float: ...
    @overload
    def extrapolateToPlane(
        self,
        state: StateOnPlane,
        plane: SharedPlanePtr,
        stopAtBoundary: bool = ...,
    ) -> float: ...
    @overload
    def extrapolateToPlane(
        self,
        state: StateOnPlane,
        pos: TVector3,
        direction: TVector3,
    ) -> float: ...
    def getMom(self, state: StateOnPlane) -> TVector3: ...
    def getDir(self, state: StateOnPlane) -> TVector3: ...

class AbsFitterInfo:
    # Partial stub
    def getResidual(
        self,
        iMeasurement: int = ...,
        biased: bool = ...,
        onlyMeasurementErrors: bool = ...,
    ) -> MeasurementOnPlane: ...
    def getWeights(self) -> TVectorD: ...

class KalmanFitterInfo(AbsFitterInfo):
    # Partial stub
    ...

class TrackPoint:
    # Partial stub
    def __init__(self, track: Track) -> None: ...
    def addRawMeasurement(self, measurement: WireMeasurement) -> None: ...
    def getFitterInfo(self, rep: RKTrackRep | None = ...) -> AbsFitterInfo | None: ...

class Track:
    # Partial stub
    @overload
    def __init__(
        self,
        rep: RKTrackRep,
        seedState: TVectorD,
        seedCov: TMatrixDSym,
    ) -> None: ...
    @overload
    def __init__(self, otherTrack: Self) -> None: ...
    def insertPoint(self, tp: TrackPoint) -> None: ...
    def checkConsistency(self) -> bool: ...
    def getPoint(self, id: int) -> TrackPoint: ...
    @overload
    def getFittedState(self, id: int) -> MeasuredStateOnPlane: ...
    @overload
    def getFittedState(self, rep: RKTrackRep | None = ...) -> MeasuredStateOnPlane: ...
    def getNumPointsWithMeasurement(self) -> int: ...
    def getPointWithMeasurement(self, i: int) -> TrackPoint: ...
    def getFitStatus(self, rep: RKTrackRep | None = ...) -> FitStatus: ...

class DetPlane:
    # Partial stub
    @overload
    def __init__(self, pos: TVector3, normal: TVector3) -> None: ...
    @overload
    def __init__(self, pos: TVector3, u_vec: TVector3, v_vec: TVector3) -> None: ...

class SharedPlanePtr:
    # Partial stub
    def __init__(self, plane: DetPlane) -> None: ...

class WireMeasurement:
    # Partial stub
    def __init__(
        self,
        m: TVectorD,
        hitCov: TMatrixDSym,
        detID: int,
        hitID: int,
        tp: TrackPoint,
    ) -> None: ...
    def setMaxDistance(self, d: float) -> None: ...
    def setLeftRightResolution(self, lr: int) -> None: ...

class FitStatus:
    # Partial stub
    def isFitConverged(self) -> bool: ...
    def getNdf(self) -> float: ...
    def getChi2(self) -> float: ...

class DAF:
    # Partial stub
    def __init__(self) -> None: ...
    def setMaxIterations(self, n: int) -> None: ...
    def setDebugLvl(self, n: int) -> None: ...
    def processTrack(self, track: Track) -> None: ...
    def processTrackWithRep(
        self,
        track: Track,
        rep: RKTrackRep,
        resortHits: bool,
    ) -> None: ...

class KalmanFitter:
    # Partial stub
    def __init__(self) -> None: ...
    def setMaxIterations(self, n: int) -> None: ...
    def setDebugLvl(self, n: int) -> None: ...
    def processTrack(self, track: Track) -> None: ...
    def processTrackWithRep(
        self,
        track: Track,
        rep: RKTrackRep,
        resortHits: bool,
    ) -> None: ...

class KalmanFitterRefTrack:
    # Partial stub
    def __init__(self) -> None: ...
    def setMaxIterations(self, n: int) -> None: ...
    def setDebugLvl(self, n: int) -> None: ...
    def processTrack(self, track: Track) -> None: ...
    def processTrackWithRep(
        self,
        track: Track,
        rep: RKTrackRep,
        resortHits: bool,
    ) -> None: ...

class Exception(BaseException):
    # Partial stub
    def what(self) -> str: ...

class tools:
    # Partial stub
    @staticmethod
    def invertMatrix(matrix: TMatrixDSym, result: TMatrixDSym) -> None: ...
