name: Pixi Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: pixi-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: ShipSoft/.github/.github/workflows/pixi-cmake-build.yml@main
    with:
      lfs: true
      tasks: '["configure", "build", "test", "ci-sim"]'
      env-vars: |
        QT_QPA_PLATFORM=offscreen
