on:
  push:
    branches:
      - 'self-hosted-test'
jobs:
  testing:
    strategy:
      fail-fast: false
    runs-on: self-hosted
    container:
      image: gitlab-registry.cern.ch/linuxsupport/alma9-base
      volumes:
        - /cvmfs/sft.cern.ch/:/cvmfs/sft.cern.ch/
    steps:
      - name: Just echo something
        run: echo "Hola amigo"
      - name: Check cvmfs access
        run: ls -l /cvmfs/sft.cern.ch/
