on:
  push:
    branches:
      - 'self-hosted-test'

jobs:
  testing:
    strategy:
      fail-fast: false

    runs-on: self-hosted

    container:
      image: registry.cern.ch/ship/gha-runner
      volumes:
        - /cvmfs/sft.cern.ch/:/cvmfs/sft.cern.ch/
        - /cvmfs/ship.cern.ch/:/cvmfs/ship.cern.ch/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Source environment setup
        run: source /cvmfs/ship.cern.ch/24.10/setUp.sh

      - name: Build software
        run: aliBuild build FairShip --always-prefer-system --config-dir $SHIPDIST --defaults release
